//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace Vincontrol.Payment.com.securenet.transactionServices {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_ITRANSACTION", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RESPONSE))]
    public partial class TRANSACTION : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetTransactionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTransactionByTransactionIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTransactionByOrderIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBatchTransactionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCurrentBatchIDOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TRANSACTION() {
            this.Url = "http://certify.securenet.com/API/DATA/TRANSACTION.svc/soap";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetTransactionsCompletedEventHandler GetTransactionsCompleted;
        
        /// <remarks/>
        public event GetTransactionByTransactionIDCompletedEventHandler GetTransactionByTransactionIDCompleted;
        
        /// <remarks/>
        public event GetTransactionByOrderIDCompletedEventHandler GetTransactionByOrderIDCompleted;
        
        /// <remarks/>
        public event GetBatchTransactionsCompletedEventHandler GetBatchTransactionsCompleted;
        
        /// <remarks/>
        public event GetCurrentBatchIDCompletedEventHandler GetCurrentBatchIDCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://gateway.securenet.com/API/DATA/ITRANSACTION/GetTransactions", RequestNamespace="http://gateway.securenet.com/API/DATA/", ResponseNamespace="http://gateway.securenet.com/API/DATA/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://gateway.securenet.com/API/Contracts")]
        public TRANSACTIONRESPONSE[] GetTransactions([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] MERCHANT_KEY MerchantKey, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string StartDate, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string EndDate, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string ExcludeDate, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string CustomerID, decimal Amount, [System.Xml.Serialization.XmlIgnoreAttribute()] bool AmountSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string RBOnly) {
            object[] results = this.Invoke("GetTransactions", new object[] {
                        MerchantKey,
                        StartDate,
                        EndDate,
                        ExcludeDate,
                        CustomerID,
                        Amount,
                        AmountSpecified,
                        RBOnly});
            return ((TRANSACTIONRESPONSE[])(results[0]));
        }
        
        /// <remarks/>
        public void GetTransactionsAsync(MERCHANT_KEY MerchantKey, string StartDate, string EndDate, string ExcludeDate, string CustomerID, decimal Amount, bool AmountSpecified, string RBOnly) {
            this.GetTransactionsAsync(MerchantKey, StartDate, EndDate, ExcludeDate, CustomerID, Amount, AmountSpecified, RBOnly, null);
        }
        
        /// <remarks/>
        public void GetTransactionsAsync(MERCHANT_KEY MerchantKey, string StartDate, string EndDate, string ExcludeDate, string CustomerID, decimal Amount, bool AmountSpecified, string RBOnly, object userState) {
            if ((this.GetTransactionsOperationCompleted == null)) {
                this.GetTransactionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTransactionsOperationCompleted);
            }
            this.InvokeAsync("GetTransactions", new object[] {
                        MerchantKey,
                        StartDate,
                        EndDate,
                        ExcludeDate,
                        CustomerID,
                        Amount,
                        AmountSpecified,
                        RBOnly}, this.GetTransactionsOperationCompleted, userState);
        }
        
        private void OnGetTransactionsOperationCompleted(object arg) {
            if ((this.GetTransactionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTransactionsCompleted(this, new GetTransactionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://gateway.securenet.com/API/DATA/ITRANSACTION/GetTransactionByTransactionID", RequestNamespace="http://gateway.securenet.com/API/DATA/", ResponseNamespace="http://gateway.securenet.com/API/DATA/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public TRANSACTIONRESPONSE GetTransactionByTransactionID([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] MERCHANT_KEY MerchantKey, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string TransactionID) {
            object[] results = this.Invoke("GetTransactionByTransactionID", new object[] {
                        MerchantKey,
                        TransactionID});
            return ((TRANSACTIONRESPONSE)(results[0]));
        }
        
        /// <remarks/>
        public void GetTransactionByTransactionIDAsync(MERCHANT_KEY MerchantKey, string TransactionID) {
            this.GetTransactionByTransactionIDAsync(MerchantKey, TransactionID, null);
        }
        
        /// <remarks/>
        public void GetTransactionByTransactionIDAsync(MERCHANT_KEY MerchantKey, string TransactionID, object userState) {
            if ((this.GetTransactionByTransactionIDOperationCompleted == null)) {
                this.GetTransactionByTransactionIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTransactionByTransactionIDOperationCompleted);
            }
            this.InvokeAsync("GetTransactionByTransactionID", new object[] {
                        MerchantKey,
                        TransactionID}, this.GetTransactionByTransactionIDOperationCompleted, userState);
        }
        
        private void OnGetTransactionByTransactionIDOperationCompleted(object arg) {
            if ((this.GetTransactionByTransactionIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTransactionByTransactionIDCompleted(this, new GetTransactionByTransactionIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://gateway.securenet.com/API/DATA/ITRANSACTION/GetTransactionByOrderID", RequestNamespace="http://gateway.securenet.com/API/DATA/", ResponseNamespace="http://gateway.securenet.com/API/DATA/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public TRANSACTIONRESPONSE GetTransactionByOrderID([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] MERCHANT_KEY MerchantKey, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string OrderID) {
            object[] results = this.Invoke("GetTransactionByOrderID", new object[] {
                        MerchantKey,
                        OrderID});
            return ((TRANSACTIONRESPONSE)(results[0]));
        }
        
        /// <remarks/>
        public void GetTransactionByOrderIDAsync(MERCHANT_KEY MerchantKey, string OrderID) {
            this.GetTransactionByOrderIDAsync(MerchantKey, OrderID, null);
        }
        
        /// <remarks/>
        public void GetTransactionByOrderIDAsync(MERCHANT_KEY MerchantKey, string OrderID, object userState) {
            if ((this.GetTransactionByOrderIDOperationCompleted == null)) {
                this.GetTransactionByOrderIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTransactionByOrderIDOperationCompleted);
            }
            this.InvokeAsync("GetTransactionByOrderID", new object[] {
                        MerchantKey,
                        OrderID}, this.GetTransactionByOrderIDOperationCompleted, userState);
        }
        
        private void OnGetTransactionByOrderIDOperationCompleted(object arg) {
            if ((this.GetTransactionByOrderIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTransactionByOrderIDCompleted(this, new GetTransactionByOrderIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://gateway.securenet.com/API/DATA/ITRANSACTION/GetBatchTransactions", RequestNamespace="http://gateway.securenet.com/API/DATA/", ResponseNamespace="http://gateway.securenet.com/API/DATA/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://gateway.securenet.com/API/Contracts")]
        public TRANSACTIONRESPONSE[] GetBatchTransactions([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] MERCHANT_KEY MerchantKey, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string BatchID) {
            object[] results = this.Invoke("GetBatchTransactions", new object[] {
                        MerchantKey,
                        BatchID});
            return ((TRANSACTIONRESPONSE[])(results[0]));
        }
        
        /// <remarks/>
        public void GetBatchTransactionsAsync(MERCHANT_KEY MerchantKey, string BatchID) {
            this.GetBatchTransactionsAsync(MerchantKey, BatchID, null);
        }
        
        /// <remarks/>
        public void GetBatchTransactionsAsync(MERCHANT_KEY MerchantKey, string BatchID, object userState) {
            if ((this.GetBatchTransactionsOperationCompleted == null)) {
                this.GetBatchTransactionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBatchTransactionsOperationCompleted);
            }
            this.InvokeAsync("GetBatchTransactions", new object[] {
                        MerchantKey,
                        BatchID}, this.GetBatchTransactionsOperationCompleted, userState);
        }
        
        private void OnGetBatchTransactionsOperationCompleted(object arg) {
            if ((this.GetBatchTransactionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBatchTransactionsCompleted(this, new GetBatchTransactionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://gateway.securenet.com/API/DATA/ITRANSACTION/GetCurrentBatchID", RequestNamespace="http://gateway.securenet.com/API/DATA/", ResponseNamespace="http://gateway.securenet.com/API/DATA/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetCurrentBatchID([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] MERCHANT_KEY MerchantKey) {
            object[] results = this.Invoke("GetCurrentBatchID", new object[] {
                        MerchantKey});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCurrentBatchIDAsync(MERCHANT_KEY MerchantKey) {
            this.GetCurrentBatchIDAsync(MerchantKey, null);
        }
        
        /// <remarks/>
        public void GetCurrentBatchIDAsync(MERCHANT_KEY MerchantKey, object userState) {
            if ((this.GetCurrentBatchIDOperationCompleted == null)) {
                this.GetCurrentBatchIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCurrentBatchIDOperationCompleted);
            }
            this.InvokeAsync("GetCurrentBatchID", new object[] {
                        MerchantKey}, this.GetCurrentBatchIDOperationCompleted, userState);
        }
        
        private void OnGetCurrentBatchIDOperationCompleted(object arg) {
            if ((this.GetCurrentBatchIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCurrentBatchIDCompleted(this, new GetCurrentBatchIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gateway.securenet.com/API/Contracts")]
    public partial class MERCHANT_KEY {
        
        private int gROUPIDField;
        
        private string sECUREKEYField;
        
        private int sECURENETIDField;
        
        private string aDDITIONALINFOField;
        
        /// <remarks/>
        public int GROUPID {
            get {
                return this.gROUPIDField;
            }
            set {
                this.gROUPIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SECUREKEY {
            get {
                return this.sECUREKEYField;
            }
            set {
                this.sECUREKEYField = value;
            }
        }
        
        /// <remarks/>
        public int SECURENETID {
            get {
                return this.sECURENETIDField;
            }
            set {
                this.sECURENETIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ADDITIONALINFO {
            get {
                return this.aDDITIONALINFOField;
            }
            set {
                this.aDDITIONALINFOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gateway.securenet.com/API/Contracts")]
    public partial class CUSTOMER_BILL {
        
        private string aDDRESSField;
        
        private string cITYField;
        
        private string cOMPANYField;
        
        private string cOUNTRYField;
        
        private string eMAILField;
        
        private string eMAILRECEIPTField;
        
        private string fIRSTNAMEField;
        
        private string lASTNAMEField;
        
        private string pHONEField;
        
        private string sTATEField;
        
        private string zIPField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ADDRESS {
            get {
                return this.aDDRESSField;
            }
            set {
                this.aDDRESSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CITY {
            get {
                return this.cITYField;
            }
            set {
                this.cITYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string COMPANY {
            get {
                return this.cOMPANYField;
            }
            set {
                this.cOMPANYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string COUNTRY {
            get {
                return this.cOUNTRYField;
            }
            set {
                this.cOUNTRYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EMAIL {
            get {
                return this.eMAILField;
            }
            set {
                this.eMAILField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EMAILRECEIPT {
            get {
                return this.eMAILRECEIPTField;
            }
            set {
                this.eMAILRECEIPTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FIRSTNAME {
            get {
                return this.fIRSTNAMEField;
            }
            set {
                this.fIRSTNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LASTNAME {
            get {
                return this.lASTNAMEField;
            }
            set {
                this.lASTNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PHONE {
            get {
                return this.pHONEField;
            }
            set {
                this.pHONEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string STATE {
            get {
                return this.sTATEField;
            }
            set {
                this.sTATEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ZIP {
            get {
                return this.zIPField;
            }
            set {
                this.zIPField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TRANSACTIONRESPONSE))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gateway.securenet.com/API/Contracts")]
    public partial class RESPONSE {
        
        private string rESPONSE_CODEField;
        
        private string rESPONSE_REASON_CODEField;
        
        private string rESPONSE_REASON_TEXTField;
        
        private string rESPONSE_SUBCODEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RESPONSE_CODE {
            get {
                return this.rESPONSE_CODEField;
            }
            set {
                this.rESPONSE_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RESPONSE_REASON_CODE {
            get {
                return this.rESPONSE_REASON_CODEField;
            }
            set {
                this.rESPONSE_REASON_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RESPONSE_REASON_TEXT {
            get {
                return this.rESPONSE_REASON_TEXTField;
            }
            set {
                this.rESPONSE_REASON_TEXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RESPONSE_SUBCODE {
            get {
                return this.rESPONSE_SUBCODEField;
            }
            set {
                this.rESPONSE_SUBCODEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gateway.securenet.com/API/Contracts")]
    public partial class TRANSACTIONRESPONSE : RESPONSE {
        
        private decimal aDDITIONALAMOUNTField;
        
        private bool aDDITIONALAMOUNTFieldSpecified;
        
        private string aDDITIONALDATA1Field;
        
        private string aDDITIONALDATA2Field;
        
        private string aDDITIONALDATA3Field;
        
        private string aDDITIONALDATA4Field;
        
        private string aDDITIONALDATA5Field;
        
        private string aUTHCODEField;
        
        private decimal aUTHORIZEDAMOUNTField;
        
        private bool aUTHORIZEDAMOUNTFieldSpecified;
        
        private string aVS_RESULT_CODEField;
        
        private string bANK_ACCOUNTNAMEField;
        
        private string bANK_ACCOUNTTYPEField;
        
        private string bATCHIDField;
        
        private string cARDHOLDER_FIRSTNAMEField;
        
        private string cARDHOLDER_LASTNAMEField;
        
        private string cARDLEVEL_RESULTSField;
        
        private string cARDTYPEField;
        
        private string cARD_CODE_RESPONSE_CODEField;
        
        private decimal cASHBACK_AMOUNTField;
        
        private bool cASHBACK_AMOUNTFieldSpecified;
        
        private string cAVV_RESPONSE_CODEField;
        
        private string cHECKNUMField;
        
        private string cODEField;
        
        private string cUSTOMERIDField;
        
        private CUSTOMER_BILL cUSTOMER_BILLField;
        
        private string eXPIRYDATEField;
        
        private decimal gRATUITYField;
        
        private bool gRATUITYFieldSpecified;
        
        private string iNDUSTRYSPECIFICDATAField;
        
        private string lAST4DIGITSField;
        
        private string lEVEL2_VALIDField;
        
        private string lEVEL3_VALIDField;
        
        private string mARKETSPECIFICDATAField;
        
        private string mETHODField;
        
        private string nETWORKCODEField;
        
        private string nETWORKIDField;
        
        private string oRDERIDField;
        
        private string pAYMENTIDField;
        
        private string rETREFERENCENUMField;
        
        private int sECURENETIDField;
        
        private bool sECURENETIDFieldSpecified;
        
        private decimal sETTLEMENTAMOUNTField;
        
        private bool sETTLEMENTAMOUNTFieldSpecified;
        
        private string sETTLEMENTDATETIMEField;
        
        private string sYSTEM_TRACENUMField;
        
        private string tRACKTYPEField;
        
        private decimal tRANSACTIONAMOUNTField;
        
        private bool tRANSACTIONAMOUNTFieldSpecified;
        
        private string tRANSACTIONDATETIMEField;
        
        private int tRANSACTIONIDField;
        
        private bool tRANSACTIONIDFieldSpecified;
        
        /// <remarks/>
        public decimal ADDITIONALAMOUNT {
            get {
                return this.aDDITIONALAMOUNTField;
            }
            set {
                this.aDDITIONALAMOUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ADDITIONALAMOUNTSpecified {
            get {
                return this.aDDITIONALAMOUNTFieldSpecified;
            }
            set {
                this.aDDITIONALAMOUNTFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ADDITIONALDATA1 {
            get {
                return this.aDDITIONALDATA1Field;
            }
            set {
                this.aDDITIONALDATA1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ADDITIONALDATA2 {
            get {
                return this.aDDITIONALDATA2Field;
            }
            set {
                this.aDDITIONALDATA2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ADDITIONALDATA3 {
            get {
                return this.aDDITIONALDATA3Field;
            }
            set {
                this.aDDITIONALDATA3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ADDITIONALDATA4 {
            get {
                return this.aDDITIONALDATA4Field;
            }
            set {
                this.aDDITIONALDATA4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ADDITIONALDATA5 {
            get {
                return this.aDDITIONALDATA5Field;
            }
            set {
                this.aDDITIONALDATA5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AUTHCODE {
            get {
                return this.aUTHCODEField;
            }
            set {
                this.aUTHCODEField = value;
            }
        }
        
        /// <remarks/>
        public decimal AUTHORIZEDAMOUNT {
            get {
                return this.aUTHORIZEDAMOUNTField;
            }
            set {
                this.aUTHORIZEDAMOUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AUTHORIZEDAMOUNTSpecified {
            get {
                return this.aUTHORIZEDAMOUNTFieldSpecified;
            }
            set {
                this.aUTHORIZEDAMOUNTFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AVS_RESULT_CODE {
            get {
                return this.aVS_RESULT_CODEField;
            }
            set {
                this.aVS_RESULT_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BANK_ACCOUNTNAME {
            get {
                return this.bANK_ACCOUNTNAMEField;
            }
            set {
                this.bANK_ACCOUNTNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BANK_ACCOUNTTYPE {
            get {
                return this.bANK_ACCOUNTTYPEField;
            }
            set {
                this.bANK_ACCOUNTTYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BATCHID {
            get {
                return this.bATCHIDField;
            }
            set {
                this.bATCHIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CARDHOLDER_FIRSTNAME {
            get {
                return this.cARDHOLDER_FIRSTNAMEField;
            }
            set {
                this.cARDHOLDER_FIRSTNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CARDHOLDER_LASTNAME {
            get {
                return this.cARDHOLDER_LASTNAMEField;
            }
            set {
                this.cARDHOLDER_LASTNAMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CARDLEVEL_RESULTS {
            get {
                return this.cARDLEVEL_RESULTSField;
            }
            set {
                this.cARDLEVEL_RESULTSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CARDTYPE {
            get {
                return this.cARDTYPEField;
            }
            set {
                this.cARDTYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CARD_CODE_RESPONSE_CODE {
            get {
                return this.cARD_CODE_RESPONSE_CODEField;
            }
            set {
                this.cARD_CODE_RESPONSE_CODEField = value;
            }
        }
        
        /// <remarks/>
        public decimal CASHBACK_AMOUNT {
            get {
                return this.cASHBACK_AMOUNTField;
            }
            set {
                this.cASHBACK_AMOUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CASHBACK_AMOUNTSpecified {
            get {
                return this.cASHBACK_AMOUNTFieldSpecified;
            }
            set {
                this.cASHBACK_AMOUNTFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CAVV_RESPONSE_CODE {
            get {
                return this.cAVV_RESPONSE_CODEField;
            }
            set {
                this.cAVV_RESPONSE_CODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CHECKNUM {
            get {
                return this.cHECKNUMField;
            }
            set {
                this.cHECKNUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CODE {
            get {
                return this.cODEField;
            }
            set {
                this.cODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CUSTOMERID {
            get {
                return this.cUSTOMERIDField;
            }
            set {
                this.cUSTOMERIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public CUSTOMER_BILL CUSTOMER_BILL {
            get {
                return this.cUSTOMER_BILLField;
            }
            set {
                this.cUSTOMER_BILLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string EXPIRYDATE {
            get {
                return this.eXPIRYDATEField;
            }
            set {
                this.eXPIRYDATEField = value;
            }
        }
        
        /// <remarks/>
        public decimal GRATUITY {
            get {
                return this.gRATUITYField;
            }
            set {
                this.gRATUITYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GRATUITYSpecified {
            get {
                return this.gRATUITYFieldSpecified;
            }
            set {
                this.gRATUITYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string INDUSTRYSPECIFICDATA {
            get {
                return this.iNDUSTRYSPECIFICDATAField;
            }
            set {
                this.iNDUSTRYSPECIFICDATAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LAST4DIGITS {
            get {
                return this.lAST4DIGITSField;
            }
            set {
                this.lAST4DIGITSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LEVEL2_VALID {
            get {
                return this.lEVEL2_VALIDField;
            }
            set {
                this.lEVEL2_VALIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string LEVEL3_VALID {
            get {
                return this.lEVEL3_VALIDField;
            }
            set {
                this.lEVEL3_VALIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MARKETSPECIFICDATA {
            get {
                return this.mARKETSPECIFICDATAField;
            }
            set {
                this.mARKETSPECIFICDATAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string METHOD {
            get {
                return this.mETHODField;
            }
            set {
                this.mETHODField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NETWORKCODE {
            get {
                return this.nETWORKCODEField;
            }
            set {
                this.nETWORKCODEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string NETWORKID {
            get {
                return this.nETWORKIDField;
            }
            set {
                this.nETWORKIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ORDERID {
            get {
                return this.oRDERIDField;
            }
            set {
                this.oRDERIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PAYMENTID {
            get {
                return this.pAYMENTIDField;
            }
            set {
                this.pAYMENTIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RETREFERENCENUM {
            get {
                return this.rETREFERENCENUMField;
            }
            set {
                this.rETREFERENCENUMField = value;
            }
        }
        
        /// <remarks/>
        public int SECURENETID {
            get {
                return this.sECURENETIDField;
            }
            set {
                this.sECURENETIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SECURENETIDSpecified {
            get {
                return this.sECURENETIDFieldSpecified;
            }
            set {
                this.sECURENETIDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal SETTLEMENTAMOUNT {
            get {
                return this.sETTLEMENTAMOUNTField;
            }
            set {
                this.sETTLEMENTAMOUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SETTLEMENTAMOUNTSpecified {
            get {
                return this.sETTLEMENTAMOUNTFieldSpecified;
            }
            set {
                this.sETTLEMENTAMOUNTFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SETTLEMENTDATETIME {
            get {
                return this.sETTLEMENTDATETIMEField;
            }
            set {
                this.sETTLEMENTDATETIMEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SYSTEM_TRACENUM {
            get {
                return this.sYSTEM_TRACENUMField;
            }
            set {
                this.sYSTEM_TRACENUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TRACKTYPE {
            get {
                return this.tRACKTYPEField;
            }
            set {
                this.tRACKTYPEField = value;
            }
        }
        
        /// <remarks/>
        public decimal TRANSACTIONAMOUNT {
            get {
                return this.tRANSACTIONAMOUNTField;
            }
            set {
                this.tRANSACTIONAMOUNTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TRANSACTIONAMOUNTSpecified {
            get {
                return this.tRANSACTIONAMOUNTFieldSpecified;
            }
            set {
                this.tRANSACTIONAMOUNTFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string TRANSACTIONDATETIME {
            get {
                return this.tRANSACTIONDATETIMEField;
            }
            set {
                this.tRANSACTIONDATETIMEField = value;
            }
        }
        
        /// <remarks/>
        public int TRANSACTIONID {
            get {
                return this.tRANSACTIONIDField;
            }
            set {
                this.tRANSACTIONIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TRANSACTIONIDSpecified {
            get {
                return this.tRANSACTIONIDFieldSpecified;
            }
            set {
                this.tRANSACTIONIDFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetTransactionsCompletedEventHandler(object sender, GetTransactionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTransactionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTransactionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TRANSACTIONRESPONSE[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TRANSACTIONRESPONSE[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetTransactionByTransactionIDCompletedEventHandler(object sender, GetTransactionByTransactionIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTransactionByTransactionIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTransactionByTransactionIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TRANSACTIONRESPONSE Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TRANSACTIONRESPONSE)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetTransactionByOrderIDCompletedEventHandler(object sender, GetTransactionByOrderIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTransactionByOrderIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTransactionByOrderIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TRANSACTIONRESPONSE Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TRANSACTIONRESPONSE)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetBatchTransactionsCompletedEventHandler(object sender, GetBatchTransactionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBatchTransactionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBatchTransactionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TRANSACTIONRESPONSE[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TRANSACTIONRESPONSE[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetCurrentBatchIDCompletedEventHandler(object sender, GetCurrentBatchIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCurrentBatchIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCurrentBatchIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591