//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("VinCommercialTruckModel", "FK_CommercialTruck_CommercialTruck", "CommercialTruckDealer", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(vincontrol.Data.Model.Truck.CommercialTruckDealer), "CommercialTruck", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(vincontrol.Data.Model.Truck.CommercialTruck), true)]
[assembly: EdmRelationshipAttribute("VinCommercialTruckModel", "FK_CommercialTruckSoldOut_CommercialTruckSoldOut", "CommercialTruckDealer", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(vincontrol.Data.Model.Truck.CommercialTruckDealer), "CommercialTruckSoldOut", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(vincontrol.Data.Model.Truck.CommercialTruckSoldOut), true)]

#endregion

namespace vincontrol.Data.Model.Truck
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class VinCommercialTruckEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new VinCommercialTruckEntities object using the connection string found in the 'VinCommercialTruckEntities' section of the application configuration file.
        /// </summary>
        public VinCommercialTruckEntities() : base("name=VinCommercialTruckEntities", "VinCommercialTruckEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new VinCommercialTruckEntities object.
        /// </summary>
        public VinCommercialTruckEntities(string connectionString) : base(connectionString, "VinCommercialTruckEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new VinCommercialTruckEntities object.
        /// </summary>
        public VinCommercialTruckEntities(EntityConnection connection) : base(connection, "VinCommercialTruckEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CommercialTruck> CommercialTrucks
        {
            get
            {
                if ((_CommercialTrucks == null))
                {
                    _CommercialTrucks = base.CreateObjectSet<CommercialTruck>("CommercialTrucks");
                }
                return _CommercialTrucks;
            }
        }
        private ObjectSet<CommercialTruck> _CommercialTrucks;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CommercialTruckSoldOut> CommercialTruckSoldOuts
        {
            get
            {
                if ((_CommercialTruckSoldOuts == null))
                {
                    _CommercialTruckSoldOuts = base.CreateObjectSet<CommercialTruckSoldOut>("CommercialTruckSoldOuts");
                }
                return _CommercialTruckSoldOuts;
            }
        }
        private ObjectSet<CommercialTruckSoldOut> _CommercialTruckSoldOuts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CommercialTruckDealer> CommercialTruckDealers
        {
            get
            {
                if ((_CommercialTruckDealers == null))
                {
                    _CommercialTruckDealers = base.CreateObjectSet<CommercialTruckDealer>("CommercialTruckDealers");
                }
                return _CommercialTruckDealers;
            }
        }
        private ObjectSet<CommercialTruckDealer> _CommercialTruckDealers;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CommercialTrucks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCommercialTrucks(CommercialTruck commercialTruck)
        {
            base.AddObject("CommercialTrucks", commercialTruck);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CommercialTruckSoldOuts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCommercialTruckSoldOuts(CommercialTruckSoldOut commercialTruckSoldOut)
        {
            base.AddObject("CommercialTruckSoldOuts", commercialTruckSoldOut);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CommercialTruckDealers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCommercialTruckDealers(CommercialTruckDealer commercialTruckDealer)
        {
            base.AddObject("CommercialTruckDealers", commercialTruckDealer);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VinCommercialTruckModel", Name="CommercialTruck")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CommercialTruck : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CommercialTruck object.
        /// </summary>
        /// <param name="truckId">Initial value of the TruckId property.</param>
        /// <param name="commercialTruckId">Initial value of the CommercialTruckId property.</param>
        /// <param name="year">Initial value of the Year property.</param>
        /// <param name="make">Initial value of the Make property.</param>
        /// <param name="model">Initial value of the Model property.</param>
        /// <param name="price">Initial value of the Price property.</param>
        /// <param name="mileage">Initial value of the Mileage property.</param>
        /// <param name="isNew">Initial value of the IsNew property.</param>
        /// <param name="dateStamp">Initial value of the DateStamp property.</param>
        /// <param name="updated">Initial value of the Updated property.</param>
        public static CommercialTruck CreateCommercialTruck(global::System.Int32 truckId, global::System.Int32 commercialTruckId, global::System.Int32 year, global::System.String make, global::System.String model, global::System.Int32 price, global::System.Int32 mileage, global::System.Boolean isNew, global::System.DateTime dateStamp, global::System.DateTime updated)
        {
            CommercialTruck commercialTruck = new CommercialTruck();
            commercialTruck.TruckId = truckId;
            commercialTruck.CommercialTruckId = commercialTruckId;
            commercialTruck.Year = year;
            commercialTruck.Make = make;
            commercialTruck.Model = model;
            commercialTruck.Price = price;
            commercialTruck.Mileage = mileage;
            commercialTruck.IsNew = isNew;
            commercialTruck.DateStamp = dateStamp;
            commercialTruck.Updated = updated;
            return commercialTruck;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TruckId
        {
            get
            {
                return _TruckId;
            }
            set
            {
                if (_TruckId != value)
                {
                    OnTruckIdChanging(value);
                    ReportPropertyChanging("TruckId");
                    _TruckId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TruckId");
                    OnTruckIdChanged();
                }
            }
        }
        private global::System.Int32 _TruckId;
        partial void OnTruckIdChanging(global::System.Int32 value);
        partial void OnTruckIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CommercialTruckId
        {
            get
            {
                return _CommercialTruckId;
            }
            set
            {
                OnCommercialTruckIdChanging(value);
                ReportPropertyChanging("CommercialTruckId");
                _CommercialTruckId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CommercialTruckId");
                OnCommercialTruckIdChanged();
            }
        }
        private global::System.Int32 _CommercialTruckId;
        partial void OnCommercialTruckIdChanging(global::System.Int32 value);
        partial void OnCommercialTruckIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DealerId
        {
            get
            {
                return _DealerId;
            }
            set
            {
                OnDealerIdChanging(value);
                ReportPropertyChanging("DealerId");
                _DealerId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DealerId");
                OnDealerIdChanged();
            }
        }
        private Nullable<global::System.Int32> _DealerId;
        partial void OnDealerIdChanging(Nullable<global::System.Int32> value);
        partial void OnDealerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Year
        {
            get
            {
                return _Year;
            }
            set
            {
                OnYearChanging(value);
                ReportPropertyChanging("Year");
                _Year = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Year");
                OnYearChanged();
            }
        }
        private global::System.Int32 _Year;
        partial void OnYearChanging(global::System.Int32 value);
        partial void OnYearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Make
        {
            get
            {
                return _Make;
            }
            set
            {
                OnMakeChanging(value);
                ReportPropertyChanging("Make");
                _Make = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Make");
                OnMakeChanged();
            }
        }
        private global::System.String _Make;
        partial void OnMakeChanging(global::System.String value);
        partial void OnMakeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Model
        {
            get
            {
                return _Model;
            }
            set
            {
                OnModelChanging(value);
                ReportPropertyChanging("Model");
                _Model = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Model");
                OnModelChanged();
            }
        }
        private global::System.String _Model;
        partial void OnModelChanging(global::System.String value);
        partial void OnModelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Trim
        {
            get
            {
                return _Trim;
            }
            set
            {
                OnTrimChanging(value);
                ReportPropertyChanging("Trim");
                _Trim = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Trim");
                OnTrimChanged();
            }
        }
        private global::System.String _Trim;
        partial void OnTrimChanging(global::System.String value);
        partial void OnTrimChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Vin
        {
            get
            {
                return _Vin;
            }
            set
            {
                OnVinChanging(value);
                ReportPropertyChanging("Vin");
                _Vin = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Vin");
                OnVinChanged();
            }
        }
        private global::System.String _Vin;
        partial void OnVinChanging(global::System.String value);
        partial void OnVinChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Stock
        {
            get
            {
                return _Stock;
            }
            set
            {
                OnStockChanging(value);
                ReportPropertyChanging("Stock");
                _Stock = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Stock");
                OnStockChanged();
            }
        }
        private global::System.String _Stock;
        partial void OnStockChanging(global::System.String value);
        partial void OnStockChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ExteriorColor
        {
            get
            {
                return _ExteriorColor;
            }
            set
            {
                OnExteriorColorChanging(value);
                ReportPropertyChanging("ExteriorColor");
                _ExteriorColor = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ExteriorColor");
                OnExteriorColorChanged();
            }
        }
        private global::System.String _ExteriorColor;
        partial void OnExteriorColorChanging(global::System.String value);
        partial void OnExteriorColorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String InteriorColor
        {
            get
            {
                return _InteriorColor;
            }
            set
            {
                OnInteriorColorChanging(value);
                ReportPropertyChanging("InteriorColor");
                _InteriorColor = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("InteriorColor");
                OnInteriorColorChanged();
            }
        }
        private global::System.String _InteriorColor;
        partial void OnInteriorColorChanging(global::System.String value);
        partial void OnInteriorColorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BodyStyle
        {
            get
            {
                return _BodyStyle;
            }
            set
            {
                OnBodyStyleChanging(value);
                ReportPropertyChanging("BodyStyle");
                _BodyStyle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BodyStyle");
                OnBodyStyleChanged();
            }
        }
        private global::System.String _BodyStyle;
        partial void OnBodyStyleChanging(global::System.String value);
        partial void OnBodyStyleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Engine
        {
            get
            {
                return _Engine;
            }
            set
            {
                OnEngineChanging(value);
                ReportPropertyChanging("Engine");
                _Engine = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Engine");
                OnEngineChanged();
            }
        }
        private global::System.String _Engine;
        partial void OnEngineChanging(global::System.String value);
        partial void OnEngineChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Fuel
        {
            get
            {
                return _Fuel;
            }
            set
            {
                OnFuelChanging(value);
                ReportPropertyChanging("Fuel");
                _Fuel = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Fuel");
                OnFuelChanged();
            }
        }
        private global::System.String _Fuel;
        partial void OnFuelChanging(global::System.String value);
        partial void OnFuelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Transmission
        {
            get
            {
                return _Transmission;
            }
            set
            {
                OnTransmissionChanging(value);
                ReportPropertyChanging("Transmission");
                _Transmission = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Transmission");
                OnTransmissionChanged();
            }
        }
        private global::System.String _Transmission;
        partial void OnTransmissionChanging(global::System.String value);
        partial void OnTransmissionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DriveTrain
        {
            get
            {
                return _DriveTrain;
            }
            set
            {
                OnDriveTrainChanging(value);
                ReportPropertyChanging("DriveTrain");
                _DriveTrain = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DriveTrain");
                OnDriveTrainChanged();
            }
        }
        private global::System.String _DriveTrain;
        partial void OnDriveTrainChanging(global::System.String value);
        partial void OnDriveTrainChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
        }
        private global::System.Int32 _Price;
        partial void OnPriceChanging(global::System.Int32 value);
        partial void OnPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Mileage
        {
            get
            {
                return _Mileage;
            }
            set
            {
                OnMileageChanging(value);
                ReportPropertyChanging("Mileage");
                _Mileage = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Mileage");
                OnMileageChanged();
            }
        }
        private global::System.Int32 _Mileage;
        partial void OnMileageChanging(global::System.Int32 value);
        partial void OnMileageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Package
        {
            get
            {
                return _Package;
            }
            set
            {
                OnPackageChanging(value);
                ReportPropertyChanging("Package");
                _Package = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Package");
                OnPackageChanged();
            }
        }
        private global::System.String _Package;
        partial void OnPackageChanging(global::System.String value);
        partial void OnPackageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsNew
        {
            get
            {
                return _IsNew;
            }
            set
            {
                OnIsNewChanging(value);
                ReportPropertyChanging("IsNew");
                _IsNew = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsNew");
                OnIsNewChanged();
            }
        }
        private global::System.Boolean _IsNew;
        partial void OnIsNewChanging(global::System.Boolean value);
        partial void OnIsNewChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateStamp
        {
            get
            {
                return _DateStamp;
            }
            set
            {
                OnDateStampChanging(value);
                ReportPropertyChanging("DateStamp");
                _DateStamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateStamp");
                OnDateStampChanged();
            }
        }
        private global::System.DateTime _DateStamp;
        partial void OnDateStampChanging(global::System.DateTime value);
        partial void OnDateStampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Images
        {
            get
            {
                return _Images;
            }
            set
            {
                OnImagesChanging(value);
                ReportPropertyChanging("Images");
                _Images = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Images");
                OnImagesChanged();
            }
        }
        private global::System.String _Images;
        partial void OnImagesChanging(global::System.String value);
        partial void OnImagesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Category
        {
            get
            {
                return _Category;
            }
            set
            {
                OnCategoryChanging(value);
                ReportPropertyChanging("Category");
                _Category = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Category");
                OnCategoryChanged();
            }
        }
        private global::System.String _Category;
        partial void OnCategoryChanging(global::System.String value);
        partial void OnCategoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Class
        {
            get
            {
                return _Class;
            }
            set
            {
                OnClassChanging(value);
                ReportPropertyChanging("Class");
                _Class = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Class");
                OnClassChanged();
            }
        }
        private global::System.String _Class;
        partial void OnClassChanging(global::System.String value);
        partial void OnClassChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Url
        {
            get
            {
                return _Url;
            }
            set
            {
                OnUrlChanging(value);
                ReportPropertyChanging("Url");
                _Url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Url");
                OnUrlChanged();
            }
        }
        private global::System.String _Url;
        partial void OnUrlChanging(global::System.String value);
        partial void OnUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Litter
        {
            get
            {
                return _Litter;
            }
            set
            {
                OnLitterChanging(value);
                ReportPropertyChanging("Litter");
                _Litter = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Litter");
                OnLitterChanged();
            }
        }
        private global::System.String _Litter;
        partial void OnLitterChanging(global::System.String value);
        partial void OnLitterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Updated
        {
            get
            {
                return _Updated;
            }
            set
            {
                OnUpdatedChanging(value);
                ReportPropertyChanging("Updated");
                _Updated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Updated");
                OnUpdatedChanged();
            }
        }
        private global::System.DateTime _Updated;
        partial void OnUpdatedChanging(global::System.DateTime value);
        partial void OnUpdatedChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VinCommercialTruckModel", "FK_CommercialTruck_CommercialTruck", "CommercialTruckDealer")]
        public CommercialTruckDealer CommercialTruckDealer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CommercialTruckDealer>("VinCommercialTruckModel.FK_CommercialTruck_CommercialTruck", "CommercialTruckDealer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CommercialTruckDealer>("VinCommercialTruckModel.FK_CommercialTruck_CommercialTruck", "CommercialTruckDealer").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CommercialTruckDealer> CommercialTruckDealerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CommercialTruckDealer>("VinCommercialTruckModel.FK_CommercialTruck_CommercialTruck", "CommercialTruckDealer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CommercialTruckDealer>("VinCommercialTruckModel.FK_CommercialTruck_CommercialTruck", "CommercialTruckDealer", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VinCommercialTruckModel", Name="CommercialTruckDealer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CommercialTruckDealer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CommercialTruckDealer object.
        /// </summary>
        /// <param name="dealerId">Initial value of the DealerId property.</param>
        /// <param name="commercialTruckDealerId">Initial value of the CommercialTruckDealerId property.</param>
        /// <param name="zipCode">Initial value of the ZipCode property.</param>
        /// <param name="dateStamp">Initial value of the DateStamp property.</param>
        public static CommercialTruckDealer CreateCommercialTruckDealer(global::System.Int32 dealerId, global::System.Int32 commercialTruckDealerId, global::System.Int32 zipCode, global::System.DateTime dateStamp)
        {
            CommercialTruckDealer commercialTruckDealer = new CommercialTruckDealer();
            commercialTruckDealer.DealerId = dealerId;
            commercialTruckDealer.CommercialTruckDealerId = commercialTruckDealerId;
            commercialTruckDealer.ZipCode = zipCode;
            commercialTruckDealer.DateStamp = dateStamp;
            return commercialTruckDealer;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DealerId
        {
            get
            {
                return _DealerId;
            }
            set
            {
                if (_DealerId != value)
                {
                    OnDealerIdChanging(value);
                    ReportPropertyChanging("DealerId");
                    _DealerId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DealerId");
                    OnDealerIdChanged();
                }
            }
        }
        private global::System.Int32 _DealerId;
        partial void OnDealerIdChanging(global::System.Int32 value);
        partial void OnDealerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CommercialTruckDealerId
        {
            get
            {
                return _CommercialTruckDealerId;
            }
            set
            {
                OnCommercialTruckDealerIdChanging(value);
                ReportPropertyChanging("CommercialTruckDealerId");
                _CommercialTruckDealerId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CommercialTruckDealerId");
                OnCommercialTruckDealerIdChanged();
            }
        }
        private global::System.Int32 _CommercialTruckDealerId;
        partial void OnCommercialTruckDealerIdChanging(global::System.Int32 value);
        partial void OnCommercialTruckDealerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DealerGroupId
        {
            get
            {
                return _DealerGroupId;
            }
            set
            {
                OnDealerGroupIdChanging(value);
                ReportPropertyChanging("DealerGroupId");
                _DealerGroupId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DealerGroupId");
                OnDealerGroupIdChanged();
            }
        }
        private global::System.String _DealerGroupId;
        partial void OnDealerGroupIdChanging(global::System.String value);
        partial void OnDealerGroupIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private global::System.String _State;
        partial void OnStateChanging(global::System.String value);
        partial void OnStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ZipCode
        {
            get
            {
                return _ZipCode;
            }
            set
            {
                OnZipCodeChanging(value);
                ReportPropertyChanging("ZipCode");
                _ZipCode = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ZipCode");
                OnZipCodeChanged();
            }
        }
        private global::System.Int32 _ZipCode;
        partial void OnZipCodeChanging(global::System.Int32 value);
        partial void OnZipCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Latitude
        {
            get
            {
                return _Latitude;
            }
            set
            {
                OnLatitudeChanging(value);
                ReportPropertyChanging("Latitude");
                _Latitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Latitude");
                OnLatitudeChanged();
            }
        }
        private Nullable<global::System.Double> _Latitude;
        partial void OnLatitudeChanging(Nullable<global::System.Double> value);
        partial void OnLatitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Longitude
        {
            get
            {
                return _Longitude;
            }
            set
            {
                OnLongitudeChanging(value);
                ReportPropertyChanging("Longitude");
                _Longitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Longitude");
                OnLongitudeChanged();
            }
        }
        private Nullable<global::System.Double> _Longitude;
        partial void OnLongitudeChanging(Nullable<global::System.Double> value);
        partial void OnLongitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateStamp
        {
            get
            {
                return _DateStamp;
            }
            set
            {
                OnDateStampChanging(value);
                ReportPropertyChanging("DateStamp");
                _DateStamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateStamp");
                OnDateStampChanged();
            }
        }
        private global::System.DateTime _DateStamp;
        partial void OnDateStampChanging(global::System.DateTime value);
        partial void OnDateStampChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VinCommercialTruckModel", "FK_CommercialTruck_CommercialTruck", "CommercialTruck")]
        public EntityCollection<CommercialTruck> CommercialTrucks
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CommercialTruck>("VinCommercialTruckModel.FK_CommercialTruck_CommercialTruck", "CommercialTruck");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CommercialTruck>("VinCommercialTruckModel.FK_CommercialTruck_CommercialTruck", "CommercialTruck", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VinCommercialTruckModel", "FK_CommercialTruckSoldOut_CommercialTruckSoldOut", "CommercialTruckSoldOut")]
        public EntityCollection<CommercialTruckSoldOut> CommercialTruckSoldOuts
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CommercialTruckSoldOut>("VinCommercialTruckModel.FK_CommercialTruckSoldOut_CommercialTruckSoldOut", "CommercialTruckSoldOut");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CommercialTruckSoldOut>("VinCommercialTruckModel.FK_CommercialTruckSoldOut_CommercialTruckSoldOut", "CommercialTruckSoldOut", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VinCommercialTruckModel", Name="CommercialTruckSoldOut")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CommercialTruckSoldOut : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CommercialTruckSoldOut object.
        /// </summary>
        /// <param name="soldOutTruckId">Initial value of the SoldOutTruckId property.</param>
        /// <param name="truckId">Initial value of the TruckId property.</param>
        /// <param name="commercialTruckId">Initial value of the CommercialTruckId property.</param>
        /// <param name="year">Initial value of the Year property.</param>
        /// <param name="make">Initial value of the Make property.</param>
        /// <param name="model">Initial value of the Model property.</param>
        /// <param name="price">Initial value of the Price property.</param>
        /// <param name="mileage">Initial value of the Mileage property.</param>
        /// <param name="isNew">Initial value of the IsNew property.</param>
        /// <param name="dateStamp">Initial value of the DateStamp property.</param>
        public static CommercialTruckSoldOut CreateCommercialTruckSoldOut(global::System.Int32 soldOutTruckId, global::System.Int32 truckId, global::System.Int32 commercialTruckId, global::System.Int32 year, global::System.String make, global::System.String model, global::System.Int32 price, global::System.Int32 mileage, global::System.Boolean isNew, global::System.DateTime dateStamp)
        {
            CommercialTruckSoldOut commercialTruckSoldOut = new CommercialTruckSoldOut();
            commercialTruckSoldOut.SoldOutTruckId = soldOutTruckId;
            commercialTruckSoldOut.TruckId = truckId;
            commercialTruckSoldOut.CommercialTruckId = commercialTruckId;
            commercialTruckSoldOut.Year = year;
            commercialTruckSoldOut.Make = make;
            commercialTruckSoldOut.Model = model;
            commercialTruckSoldOut.Price = price;
            commercialTruckSoldOut.Mileage = mileage;
            commercialTruckSoldOut.IsNew = isNew;
            commercialTruckSoldOut.DateStamp = dateStamp;
            return commercialTruckSoldOut;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SoldOutTruckId
        {
            get
            {
                return _SoldOutTruckId;
            }
            set
            {
                if (_SoldOutTruckId != value)
                {
                    OnSoldOutTruckIdChanging(value);
                    ReportPropertyChanging("SoldOutTruckId");
                    _SoldOutTruckId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SoldOutTruckId");
                    OnSoldOutTruckIdChanged();
                }
            }
        }
        private global::System.Int32 _SoldOutTruckId;
        partial void OnSoldOutTruckIdChanging(global::System.Int32 value);
        partial void OnSoldOutTruckIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TruckId
        {
            get
            {
                return _TruckId;
            }
            set
            {
                OnTruckIdChanging(value);
                ReportPropertyChanging("TruckId");
                _TruckId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TruckId");
                OnTruckIdChanged();
            }
        }
        private global::System.Int32 _TruckId;
        partial void OnTruckIdChanging(global::System.Int32 value);
        partial void OnTruckIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CommercialTruckId
        {
            get
            {
                return _CommercialTruckId;
            }
            set
            {
                OnCommercialTruckIdChanging(value);
                ReportPropertyChanging("CommercialTruckId");
                _CommercialTruckId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CommercialTruckId");
                OnCommercialTruckIdChanged();
            }
        }
        private global::System.Int32 _CommercialTruckId;
        partial void OnCommercialTruckIdChanging(global::System.Int32 value);
        partial void OnCommercialTruckIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DealerId
        {
            get
            {
                return _DealerId;
            }
            set
            {
                OnDealerIdChanging(value);
                ReportPropertyChanging("DealerId");
                _DealerId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DealerId");
                OnDealerIdChanged();
            }
        }
        private Nullable<global::System.Int32> _DealerId;
        partial void OnDealerIdChanging(Nullable<global::System.Int32> value);
        partial void OnDealerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Year
        {
            get
            {
                return _Year;
            }
            set
            {
                OnYearChanging(value);
                ReportPropertyChanging("Year");
                _Year = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Year");
                OnYearChanged();
            }
        }
        private global::System.Int32 _Year;
        partial void OnYearChanging(global::System.Int32 value);
        partial void OnYearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Make
        {
            get
            {
                return _Make;
            }
            set
            {
                OnMakeChanging(value);
                ReportPropertyChanging("Make");
                _Make = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Make");
                OnMakeChanged();
            }
        }
        private global::System.String _Make;
        partial void OnMakeChanging(global::System.String value);
        partial void OnMakeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Model
        {
            get
            {
                return _Model;
            }
            set
            {
                OnModelChanging(value);
                ReportPropertyChanging("Model");
                _Model = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Model");
                OnModelChanged();
            }
        }
        private global::System.String _Model;
        partial void OnModelChanging(global::System.String value);
        partial void OnModelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Trim
        {
            get
            {
                return _Trim;
            }
            set
            {
                OnTrimChanging(value);
                ReportPropertyChanging("Trim");
                _Trim = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Trim");
                OnTrimChanged();
            }
        }
        private global::System.String _Trim;
        partial void OnTrimChanging(global::System.String value);
        partial void OnTrimChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Vin
        {
            get
            {
                return _Vin;
            }
            set
            {
                OnVinChanging(value);
                ReportPropertyChanging("Vin");
                _Vin = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Vin");
                OnVinChanged();
            }
        }
        private global::System.String _Vin;
        partial void OnVinChanging(global::System.String value);
        partial void OnVinChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Stock
        {
            get
            {
                return _Stock;
            }
            set
            {
                OnStockChanging(value);
                ReportPropertyChanging("Stock");
                _Stock = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Stock");
                OnStockChanged();
            }
        }
        private global::System.String _Stock;
        partial void OnStockChanging(global::System.String value);
        partial void OnStockChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ExteriorColor
        {
            get
            {
                return _ExteriorColor;
            }
            set
            {
                OnExteriorColorChanging(value);
                ReportPropertyChanging("ExteriorColor");
                _ExteriorColor = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ExteriorColor");
                OnExteriorColorChanged();
            }
        }
        private global::System.String _ExteriorColor;
        partial void OnExteriorColorChanging(global::System.String value);
        partial void OnExteriorColorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String InteriorColor
        {
            get
            {
                return _InteriorColor;
            }
            set
            {
                OnInteriorColorChanging(value);
                ReportPropertyChanging("InteriorColor");
                _InteriorColor = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("InteriorColor");
                OnInteriorColorChanged();
            }
        }
        private global::System.String _InteriorColor;
        partial void OnInteriorColorChanging(global::System.String value);
        partial void OnInteriorColorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BodyStyle
        {
            get
            {
                return _BodyStyle;
            }
            set
            {
                OnBodyStyleChanging(value);
                ReportPropertyChanging("BodyStyle");
                _BodyStyle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BodyStyle");
                OnBodyStyleChanged();
            }
        }
        private global::System.String _BodyStyle;
        partial void OnBodyStyleChanging(global::System.String value);
        partial void OnBodyStyleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Engine
        {
            get
            {
                return _Engine;
            }
            set
            {
                OnEngineChanging(value);
                ReportPropertyChanging("Engine");
                _Engine = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Engine");
                OnEngineChanged();
            }
        }
        private global::System.String _Engine;
        partial void OnEngineChanging(global::System.String value);
        partial void OnEngineChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Fuel
        {
            get
            {
                return _Fuel;
            }
            set
            {
                OnFuelChanging(value);
                ReportPropertyChanging("Fuel");
                _Fuel = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Fuel");
                OnFuelChanged();
            }
        }
        private global::System.String _Fuel;
        partial void OnFuelChanging(global::System.String value);
        partial void OnFuelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Transmission
        {
            get
            {
                return _Transmission;
            }
            set
            {
                OnTransmissionChanging(value);
                ReportPropertyChanging("Transmission");
                _Transmission = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Transmission");
                OnTransmissionChanged();
            }
        }
        private global::System.String _Transmission;
        partial void OnTransmissionChanging(global::System.String value);
        partial void OnTransmissionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DriveTrain
        {
            get
            {
                return _DriveTrain;
            }
            set
            {
                OnDriveTrainChanging(value);
                ReportPropertyChanging("DriveTrain");
                _DriveTrain = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DriveTrain");
                OnDriveTrainChanged();
            }
        }
        private global::System.String _DriveTrain;
        partial void OnDriveTrainChanging(global::System.String value);
        partial void OnDriveTrainChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
        }
        private global::System.Int32 _Price;
        partial void OnPriceChanging(global::System.Int32 value);
        partial void OnPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Mileage
        {
            get
            {
                return _Mileage;
            }
            set
            {
                OnMileageChanging(value);
                ReportPropertyChanging("Mileage");
                _Mileage = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Mileage");
                OnMileageChanged();
            }
        }
        private global::System.Int32 _Mileage;
        partial void OnMileageChanging(global::System.Int32 value);
        partial void OnMileageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Package
        {
            get
            {
                return _Package;
            }
            set
            {
                OnPackageChanging(value);
                ReportPropertyChanging("Package");
                _Package = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Package");
                OnPackageChanged();
            }
        }
        private global::System.String _Package;
        partial void OnPackageChanging(global::System.String value);
        partial void OnPackageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsNew
        {
            get
            {
                return _IsNew;
            }
            set
            {
                OnIsNewChanging(value);
                ReportPropertyChanging("IsNew");
                _IsNew = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsNew");
                OnIsNewChanged();
            }
        }
        private global::System.Boolean _IsNew;
        partial void OnIsNewChanging(global::System.Boolean value);
        partial void OnIsNewChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateStamp
        {
            get
            {
                return _DateStamp;
            }
            set
            {
                OnDateStampChanging(value);
                ReportPropertyChanging("DateStamp");
                _DateStamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateStamp");
                OnDateStampChanged();
            }
        }
        private global::System.DateTime _DateStamp;
        partial void OnDateStampChanging(global::System.DateTime value);
        partial void OnDateStampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Images
        {
            get
            {
                return _Images;
            }
            set
            {
                OnImagesChanging(value);
                ReportPropertyChanging("Images");
                _Images = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Images");
                OnImagesChanged();
            }
        }
        private global::System.String _Images;
        partial void OnImagesChanging(global::System.String value);
        partial void OnImagesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Category
        {
            get
            {
                return _Category;
            }
            set
            {
                OnCategoryChanging(value);
                ReportPropertyChanging("Category");
                _Category = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Category");
                OnCategoryChanged();
            }
        }
        private global::System.String _Category;
        partial void OnCategoryChanging(global::System.String value);
        partial void OnCategoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Class
        {
            get
            {
                return _Class;
            }
            set
            {
                OnClassChanging(value);
                ReportPropertyChanging("Class");
                _Class = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Class");
                OnClassChanged();
            }
        }
        private global::System.String _Class;
        partial void OnClassChanging(global::System.String value);
        partial void OnClassChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Url
        {
            get
            {
                return _Url;
            }
            set
            {
                OnUrlChanging(value);
                ReportPropertyChanging("Url");
                _Url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Url");
                OnUrlChanged();
            }
        }
        private global::System.String _Url;
        partial void OnUrlChanging(global::System.String value);
        partial void OnUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Litter
        {
            get
            {
                return _Litter;
            }
            set
            {
                OnLitterChanging(value);
                ReportPropertyChanging("Litter");
                _Litter = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Litter");
                OnLitterChanged();
            }
        }
        private global::System.String _Litter;
        partial void OnLitterChanging(global::System.String value);
        partial void OnLitterChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VinCommercialTruckModel", "FK_CommercialTruckSoldOut_CommercialTruckSoldOut", "CommercialTruckDealer")]
        public CommercialTruckDealer CommercialTruckDealer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CommercialTruckDealer>("VinCommercialTruckModel.FK_CommercialTruckSoldOut_CommercialTruckSoldOut", "CommercialTruckDealer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CommercialTruckDealer>("VinCommercialTruckModel.FK_CommercialTruckSoldOut_CommercialTruckSoldOut", "CommercialTruckDealer").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CommercialTruckDealer> CommercialTruckDealerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CommercialTruckDealer>("VinCommercialTruckModel.FK_CommercialTruckSoldOut_CommercialTruckSoldOut", "CommercialTruckDealer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CommercialTruckDealer>("VinCommercialTruckModel.FK_CommercialTruckSoldOut_CommercialTruckSoldOut", "CommercialTruckDealer", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
