//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vincontrol.WebAPI.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int AnswerId { get; set; }
        public int AppraisalId { get; set; }
        public int QuestionId { get; set; }
        public string Answer1 { get; set; }
        public string Comment { get; set; }
    
        public virtual Appraisal Appraisal { get; set; }
        public virtual Question Question { get; set; }
    }
}
