//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vincontrol.WebAPI.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appraisal
    {
        public Appraisal()
        {
            this.Answers = new HashSet<Answer>();
            this.Walkarounds = new HashSet<Walkaround>();
        }
    
        public int AppraisalId { get; set; }
        public string PackageDescription { get; set; }
        public string PhotoUrl { get; set; }
        public string AppraisalType { get; set; }
        public string Note { get; set; }
        public Nullable<short> AppraisalStatusCodeId { get; set; }
        public Nullable<bool> VinGenie { get; set; }
        public Nullable<int> VinGenieUserId { get; set; }
        public string DeviceId { get; set; }
        public string DeviceName { get; set; }
        public string KarPowerEntryId { get; set; }
        public string Location { get; set; }
        public Nullable<int> AppraisalCustomerId { get; set; }
        public Nullable<int> AppraisalById { get; set; }
        public Nullable<System.DateTime> VinGenieAppraisalDate { get; set; }
        public Nullable<System.DateTime> AppraisalDate { get; set; }
        public Nullable<int> OldAppraisalId { get; set; }
        public string Stock { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<long> Mileage { get; set; }
        public string ExteriorColor { get; set; }
        public Nullable<bool> Certified { get; set; }
        public string AdditionalOptions { get; set; }
        public string AdditionalPackages { get; set; }
        public string Descriptions { get; set; }
        public int DealerId { get; set; }
        public Nullable<int> CarRanking { get; set; }
        public string MarketTrim { get; set; }
        public Nullable<int> MarketRange { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<int> CARFAXOwner { get; set; }
        public Nullable<decimal> ACV { get; set; }
        public Nullable<decimal> DealerCost { get; set; }
        public int VehicleId { get; set; }
        public string ThumbnailUrl { get; set; }
        public string PackageDescriptions { get; set; }
        public Nullable<int> NumberOfCar { get; set; }
    
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual AppraisalStatusCode AppraisalStatusCode { get; set; }
        public virtual Dealer Dealer { get; set; }
        public virtual AppraisalCustomer AppraisalCustomer { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual Vehicle Vehicle { get; set; }
        public virtual ICollection<Walkaround> Walkarounds { get; set; }
    }
}
