//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vincontrol.WebAPI.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppraisalCustomer
    {
        public AppraisalCustomer()
        {
            this.Appraisals = new HashSet<Appraisal>();
        }
    
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Street { get; set; }
        public int AppraisalCustomerId { get; set; }
        public string SignatureUrl { get; set; }
    
        public virtual ICollection<Appraisal> Appraisals { get; set; }
    }
}
