//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vincontrol.WebAPI.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoTraderDealer
    {
        public int AutoTraderDealerId { get; set; }
        public Nullable<int> AutoTraderDealerServiceId { get; set; }
        public string FTPUsername { get; set; }
        public string FTPPassword { get; set; }
        public Nullable<int> DealerId { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
    
        public virtual Dealer Dealer { get; set; }
    }
}
