//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vincontrol.WebAPI.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlackBook
    {
        public int BlackBookId { get; set; }
        public string Vin { get; set; }
        public string Trim { get; set; }
        public Nullable<decimal> TradeInFairPrice { get; set; }
        public Nullable<decimal> TradeInGoodPrice { get; set; }
        public Nullable<decimal> TradeInVeryGoodPrice { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public Nullable<System.DateTime> Expiration { get; set; }
    }
}
