//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vincontrol.WebAPI.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BucketJumpHistory
    {
        public int BucketJumpHistoryId { get; set; }
        public int ListingId { get; set; }
        public short VehicleStatusCodeId { get; set; }
        public string AttachFile { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<int> BucketJumpDayAlert { get; set; }
        public Nullable<System.DateTime> BucketJumpCompleteDate { get; set; }
        public Nullable<decimal> RetailPrice { get; set; }
        public string UserStamp { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public Nullable<int> OldListingId { get; set; }
    
        public virtual VehicleStatusCode VehicleStatusCode { get; set; }
    }
}
