//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vincontrol.WebAPI.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Button
    {
        public Button()
        {
            this.DealerButtons = new HashSet<DealerButton>();
        }
    
        public int ButtonId { get; set; }
        public string Button1 { get; set; }
        public string Screen { get; set; }
    
        public virtual ICollection<DealerButton> DealerButtons { get; set; }
    }
}
