//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vincontrol.WebAPI.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChartSelection
    {
        public int ChartSelectionId { get; set; }
        public int ListingId { get; set; }
        public Nullable<bool> IsCarsCom { get; set; }
        public string Options { get; set; }
        public string Trims { get; set; }
        public Nullable<bool> IsCertified { get; set; }
        public Nullable<bool> IsAll { get; set; }
        public Nullable<bool> IsFranchise { get; set; }
        public Nullable<bool> IsIndependant { get; set; }
        public short VehicleStatusCodeId { get; set; }
        public bool IsNationwide { get; set; }
    
        public virtual VehicleStatusCode VehicleStatusCode { get; set; }
    }
}
