//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vincontrol.WebAPI.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataFeedCompany
    {
        public DataFeedCompany()
        {
            this.DataFeedDealers = new HashSet<DataFeedDealer>();
        }
    
        public int DataFeedCompanyId { get; set; }
        public string CompanyName { get; set; }
        public string FTPUserName { get; set; }
        public string FTPPassword { get; set; }
        public string FTPHost { get; set; }
        public Nullable<int> FTPPort { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
    
        public virtual ICollection<DataFeedDealer> DataFeedDealers { get; set; }
    }
}
