//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vincontrol.WebAPI.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataFeedDealer
    {
        public int DataFeedCompanyId { get; set; }
        public int DealerId { get; set; }
        public string DepositFileId { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
    
        public virtual DataFeedCompany DataFeedCompany { get; set; }
        public virtual Dealer Dealer { get; set; }
    }
}
