//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vincontrol.WebAPI.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dealer
    {
        public Dealer()
        {
            this.Appraisals = new HashSet<Appraisal>();
            this.AutoTraderDealers = new HashSet<AutoTraderDealer>();
            this.DataFeedDealers = new HashSet<DataFeedDealer>();
            this.Ebays = new HashSet<Ebay>();
            this.FlyerShareDealerActivities = new HashSet<FlyerShareDealerActivity>();
            this.Inventories = new HashSet<Inventory>();
            this.Rebates = new HashSet<Rebate>();
            this.SoldoutInventories = new HashSet<SoldoutInventory>();
            this.TradeInComments = new HashSet<TradeInComment>();
            this.TradeInCustomers = new HashSet<TradeInCustomer>();
            this.UserNotifications = new HashSet<UserNotification>();
            this.UserPermissions = new HashSet<UserPermission>();
            this.WarrantyTypes = new HashSet<WarrantyType>();
        }
    
        public int DealerId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> Lattitude { get; set; }
        public Nullable<decimal> Longtitude { get; set; }
        public Nullable<bool> Active { get; set; }
        public string DealerGroupId { get; set; }
        public Nullable<bool> ImportFeed { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
    
        public virtual ICollection<Appraisal> Appraisals { get; set; }
        public virtual ICollection<AutoTraderDealer> AutoTraderDealers { get; set; }
        public virtual ICollection<DataFeedDealer> DataFeedDealers { get; set; }
        public virtual DealerGroup DealerGroup { get; set; }
        public virtual ICollection<Ebay> Ebays { get; set; }
        public virtual ICollection<FlyerShareDealerActivity> FlyerShareDealerActivities { get; set; }
        public virtual ICollection<Inventory> Inventories { get; set; }
        public virtual NotificationSetting NotificationSetting { get; set; }
        public virtual ICollection<Rebate> Rebates { get; set; }
        public virtual Setting Setting { get; set; }
        public virtual ICollection<SoldoutInventory> SoldoutInventories { get; set; }
        public virtual ICollection<TradeInComment> TradeInComments { get; set; }
        public virtual ICollection<TradeInCustomer> TradeInCustomers { get; set; }
        public virtual ICollection<UserNotification> UserNotifications { get; set; }
        public virtual ICollection<UserPermission> UserPermissions { get; set; }
        public virtual ICollection<WarrantyType> WarrantyTypes { get; set; }
    }
}
