//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vincontrol.WebAPI.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DealerGroup
    {
        public DealerGroup()
        {
            this.Dealers = new HashSet<Dealer>();
            this.Users = new HashSet<User>();
        }
    
        public string DealerGroupId { get; set; }
        public string DealerGroupName { get; set; }
        public int DefaultDealerId { get; set; }
    
        public virtual ICollection<Dealer> Dealers { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
