//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vincontrol.WebAPI.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DealerButton
    {
        public int DealerButtonId { get; set; }
        public int DealerId { get; set; }
        public int GroupId { get; set; }
        public int ButtonId { get; set; }
        public bool CanSee { get; set; }
    
        public virtual Button Button { get; set; }
        public virtual Role Role { get; set; }
    }
}
