//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vincontrol.WebAPI.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DealerActivitySubTypeCode
    {
        public DealerActivitySubTypeCode()
        {
            this.AppraisalDealerActivities = new HashSet<AppraisalDealerActivity>();
            this.InventoryDealerActivities = new HashSet<InventoryDealerActivity>();
            this.UserDealerActivities = new HashSet<UserDealerActivity>();
        }
    
        public short DealerActivitySubTypeCodeId { get; set; }
        public string Value { get; set; }
    
        public virtual ICollection<AppraisalDealerActivity> AppraisalDealerActivities { get; set; }
        public virtual ICollection<InventoryDealerActivity> InventoryDealerActivities { get; set; }
        public virtual ICollection<UserDealerActivity> UserDealerActivities { get; set; }
    }
}
