//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vincontrol.WebAPI.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Description
    {
        public int DescriptionId { get; set; }
        public string Title { get; set; }
        public Nullable<bool> YesNo { get; set; }
        public string DescriptionSentence { get; set; }
    }
}
