//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vincontrol.WebAPI.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ebay
    {
        public int EbayId { get; set; }
        public int InventoryId { get; set; }
        public string EbayAdId { get; set; }
        public string EbayAdURL { get; set; }
        public int DealerId { get; set; }
        public Nullable<System.DateTime> Expiration { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
    
        public virtual Dealer Dealer { get; set; }
        public virtual Inventory Inventory { get; set; }
    }
}
