//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vincontrol.WebAPI.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlyerShareDealerActivity
    {
        public int FlyerShareDealerActivityId { get; set; }
        public string CustomerName { get; set; }
        public string CustomerEmail { get; set; }
        public int UserStampId { get; set; }
        public System.DateTime DateStamp { get; set; }
        public int DealerId { get; set; }
        public string VIN { get; set; }
        public string Stock { get; set; }
        public Nullable<int> Year { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string Trim { get; set; }
    
        public virtual Dealer Dealer { get; set; }
        public virtual User User { get; set; }
    }
}
