//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vincontrol.WebAPI.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public Inventory()
        {
            this.Ebays = new HashSet<Ebay>();
        }
    
        public int InventoryId { get; set; }
        public Nullable<decimal> DealerMsrp { get; set; }
        public Nullable<bool> Certified { get; set; }
        public string ThumbnailUrl { get; set; }
        public Nullable<System.DateTime> DateInStock { get; set; }
        public bool Condition { get; set; }
        public Nullable<int> AddToInventoryById { get; set; }
        public Nullable<int> AppraisalId { get; set; }
        public Nullable<int> WarrantyInfo { get; set; }
        public Nullable<decimal> RetailPrice { get; set; }
        public Nullable<decimal> WindowStickerPrice { get; set; }
        public Nullable<decimal> DealerDiscount { get; set; }
        public Nullable<decimal> ManufacturerRebate { get; set; }
        public Nullable<bool> PriorRental { get; set; }
        public string Disclaimer { get; set; }
        public Nullable<bool> DealerDemo { get; set; }
        public Nullable<bool> Unwind { get; set; }
        public Nullable<bool> IsFeatured { get; set; }
        public string AdditionalTitle { get; set; }
        public Nullable<bool> EnableAutoDescription { get; set; }
        public Nullable<int> DescriptionTemplateId { get; set; }
        public Nullable<int> BucketJumpCompleteDay { get; set; }
        public Nullable<bool> ACar { get; set; }
        public Nullable<bool> BrandedTitle { get; set; }
        public Nullable<int> OldInventoryId { get; set; }
        public string OldType { get; set; }
        public short InventoryStatusCodeId { get; set; }
        public string Stock { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<long> Mileage { get; set; }
        public string ExteriorColor { get; set; }
        public string AdditionalOptions { get; set; }
        public string AdditionalPackages { get; set; }
        public string Descriptions { get; set; }
        public string PhotoUrl { get; set; }
        public int DealerId { get; set; }
        public Nullable<int> CarRanking { get; set; }
        public string MarketTrim { get; set; }
        public Nullable<int> MarketRange { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<int> CarfaxOwner { get; set; }
        public Nullable<decimal> ACV { get; set; }
        public Nullable<decimal> DealerCost { get; set; }
        public Nullable<int> OldAppraisalId { get; set; }
        public int VehicleId { get; set; }
        public string PackageDescriptions { get; set; }
        public Nullable<int> NumberOfCar { get; set; }
    
        public virtual Dealer Dealer { get; set; }
        public virtual ICollection<Ebay> Ebays { get; set; }
        public virtual InventoryStatusCode InventoryStatusCode { get; set; }
        public virtual User User { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
