//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vincontrol.WebAPI.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Make
    {
        public Make()
        {
            this.YearMakes = new HashSet<YearMake>();
        }
    
        public int MakeId { get; set; }
        public string Value { get; set; }
        public Nullable<int> ChromeId { get; set; }
        public string Source { get; set; }
        public Nullable<int> ManheimServiceId { get; set; }
        public Nullable<int> KBBServiceId { get; set; }
    
        public virtual ICollection<YearMake> YearMakes { get; set; }
    }
}
