//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vincontrol.WebAPI.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManheimMakeModel
    {
        public ManheimMakeModel()
        {
            this.ManheimModelTrims = new HashSet<ManheimModelTrim>();
        }
    
        public int ManheimMakeModelId { get; set; }
        public int YearMakeId { get; set; }
        public int ModelId { get; set; }
    
        public virtual ManheimModel ManheimModel { get; set; }
        public virtual ManheimYearMake ManheimYearMake { get; set; }
        public virtual ICollection<ManheimModelTrim> ManheimModelTrims { get; set; }
    }
}
