//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vincontrol.WebAPI.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManheimTrim
    {
        public ManheimTrim()
        {
            this.ManheimModelTrims = new HashSet<ManheimModelTrim>();
        }
    
        public int ManheimTrimId { get; set; }
        public int ServiceId { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> LowestPrice { get; set; }
        public Nullable<decimal> AveragePrice { get; set; }
        public Nullable<decimal> HighestPrice { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
    
        public virtual ICollection<ManheimModelTrim> ManheimModelTrims { get; set; }
    }
}
