//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vincontrol.WebAPI.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManheimMake
    {
        public ManheimMake()
        {
            this.ManheimYearMakes = new HashSet<ManheimYearMake>();
        }
    
        public int ManheimMakeId { get; set; }
        public int ServiceId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<ManheimYearMake> ManheimYearMakes { get; set; }
    }
}
