//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vincontrol.WebAPI.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManheimModel
    {
        public ManheimModel()
        {
            this.ManheimMakeModels = new HashSet<ManheimMakeModel>();
        }
    
        public int ManheimModelId { get; set; }
        public int ServiceId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<ManheimMakeModel> ManheimMakeModels { get; set; }
    }
}
