//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vincontrol.WebAPI.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManheimValue
    {
        public int ManheimValueId { get; set; }
        public string Vin { get; set; }
        public string Trim { get; set; }
        public Nullable<decimal> AuctionLowestPrice { get; set; }
        public Nullable<decimal> AuctionAveragePrice { get; set; }
        public Nullable<decimal> AuctionHighestPrice { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<System.DateTime> Expiration { get; set; }
        public Nullable<int> TrimServiceId { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> MakeServiceId { get; set; }
        public Nullable<int> ModelServiceId { get; set; }
        public Nullable<short> VehicleStatusCodeId { get; set; }
    
        public virtual VehicleStatusCode VehicleStatusCode { get; set; }
    }
}
