//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vincontrol.WebAPI.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManheimModelTrim
    {
        public int ManheimModelTrimId { get; set; }
        public int MakeModelId { get; set; }
        public int TrimId { get; set; }
    
        public virtual ManheimMakeModel ManheimMakeModel { get; set; }
        public virtual ManheimTrim ManheimTrim { get; set; }
    }
}
