//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vincontrol.WebAPI.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Model
    {
        public Model()
        {
            this.Trims = new HashSet<Trim>();
        }
    
        public int ModelId { get; set; }
        public string Value { get; set; }
        public Nullable<int> ChromeId { get; set; }
        public int YearMakeId { get; set; }
        public string Source { get; set; }
        public Nullable<int> ManheimServiceId { get; set; }
        public Nullable<int> KBBServiceId { get; set; }
    
        public virtual YearMake YearMake { get; set; }
        public virtual ICollection<Trim> Trims { get; set; }
    }
}
