//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vincontrol.WebAPI.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        public Package()
        {
            this.TrimPackages = new HashSet<TrimPackage>();
        }
    
        public int PackageId { get; set; }
        public string ChromeId { get; set; }
        public string Value { get; set; }
        public decimal Price { get; set; }
        public string Description { get; set; }
        public string FullValue { get; set; }
    
        public virtual ICollection<TrimPackage> TrimPackages { get; set; }
    }
}
