//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vincontrol.WebAPI.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermissionCode
    {
        public PermissionCode()
        {
            this.RolePermissions = new HashSet<RolePermission>();
        }
    
        public int PermissionCodeId { get; set; }
        public string PermissionCodeText { get; set; }
        public string PermissionText { get; set; }
        public string PermissionCategory { get; set; }
        public int Indent { get; set; }
        public int ScreenOrder { get; set; }
        public string UserStamp { get; set; }
        public System.DateTime DateStamp { get; set; }
    
        public virtual ICollection<RolePermission> RolePermissions { get; set; }
    }
}
