//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vincontrol.WebAPI.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermissionValue
    {
        public PermissionValue()
        {
            this.RolePermissions = new HashSet<RolePermission>();
        }
    
        public int PermissionValueId { get; set; }
        public string PermissionValueText { get; set; }
        public string UserStamp { get; set; }
        public System.DateTime DateStamp { get; set; }
    
        public virtual ICollection<RolePermission> RolePermissions { get; set; }
    }
}
