//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vincontrol.WebAPI.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionType
    {
        public QuestionType()
        {
            this.Questions = new HashSet<Question>();
        }
    
        public int QuestionTypeId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Option { get; set; }
        public Nullable<int> Code { get; set; }
        public string Unit { get; set; }
    
        public virtual ICollection<Question> Questions { get; set; }
    }
}
