//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vincontrol.WebAPI.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.DealerButtons = new HashSet<DealerButton>();
            this.UserPermissions = new HashSet<UserPermission>();
            this.RolePermissions = new HashSet<RolePermission>();
        }
    
        public int RoleId { get; set; }
        public string RoleName { get; set; }
        public string RoleNote { get; set; }
        public string UserStamp { get; set; }
        public System.DateTime DateStamp { get; set; }
    
        public virtual ICollection<DealerButton> DealerButtons { get; set; }
        public virtual ICollection<UserPermission> UserPermissions { get; set; }
        public virtual ICollection<RolePermission> RolePermissions { get; set; }
    }
}
