//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vincontrol.WebAPI.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolePermission
    {
        public int RolePermissionId { get; set; }
        public int RoleId { get; set; }
        public int PermissionCodeId { get; set; }
        public int PermissionValueId { get; set; }
        public string UserStamp { get; set; }
        public System.DateTime DateStamp { get; set; }
    
        public virtual PermissionCode PermissionCode { get; set; }
        public virtual PermissionValue PermissionValue { get; set; }
        public virtual Role Role { get; set; }
    }
}
