//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vincontrol.WebAPI.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public string InventorySorting { get; set; }
        public string SoldOut { get; set; }
        public int DealerId { get; set; }
        public string Ebay { get; set; }
        public string EbayPassword { get; set; }
        public string CarFax { get; set; }
        public string CarFaxPassword { get; set; }
        public string Manheim { get; set; }
        public string ManheimPassword { get; set; }
        public string KellyBlueBook { get; set; }
        public string KellyPassword { get; set; }
        public string BlackBook { get; set; }
        public string BlackBookPassword { get; set; }
        public string AutoCheck { get; set; }
        public string AutoCheckPassword { get; set; }
        public string DefaultStockImageUrl { get; set; }
        public Nullable<bool> OverideStockImage { get; set; }
        public string DealerInfo { get; set; }
        public string DealerWarranty { get; set; }
        public string TermsAndCondition { get; set; }
        public string EbayToken { get; set; }
        public string EbayInventoryUrl { get; set; }
        public string CreditUrl { get; set; }
        public string WebSiteUrl { get; set; }
        public string ContactUsUrl { get; set; }
        public string FacebookUrl { get; set; }
        public string LogoUrl { get; set; }
        public string ContactPerson { get; set; }
        public Nullable<bool> RetailPrice { get; set; }
        public Nullable<bool> DealerDiscount { get; set; }
        public Nullable<bool> ManufacturerReabte { get; set; }
        public Nullable<bool> SalePrice { get; set; }
        public string ShippingInfo { get; set; }
        public string AsIsWarranty { get; set; }
        public string AsIsWarrantySpanish { get; set; }
        public string StartDescriptionSentence { get; set; }
        public string EndDescriptionSentence { get; set; }
        public string AuctionSentence { get; set; }
        public string LoanerSentence { get; set; }
        public Nullable<int> FirstTimeRangeBucketJump { get; set; }
        public Nullable<int> SecondTimeRangeBucketJump { get; set; }
        public Nullable<int> IntervalBucketJump { get; set; }
        public string RetailPriceText { get; set; }
        public string DealerDiscountText { get; set; }
        public string ManufactureReabateText { get; set; }
        public string SalePriceText { get; set; }
        public string HeaderOverlayURL { get; set; }
        public string FooterOverlayURL { get; set; }
        public Nullable<bool> KellyBlueBookAccessRight { get; set; }
        public Nullable<bool> AutoDescription { get; set; }
        public Nullable<bool> AutoDescriptionSubscribe { get; set; }
        public Nullable<short> EmailFormat { get; set; }
        public Nullable<decimal> PriceVariance { get; set; }
        public Nullable<bool> CanViewBucketJump { get; set; }
        public string EbayContactInfoName { get; set; }
        public string EbayContactInfoPhone { get; set; }
        public string EbayContactInfoEmail { get; set; }
    
        public virtual Dealer Dealer { get; set; }
    }
}
