//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vincontrol.WebAPI.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradeInCustomer
    {
        public int TradeInCustomerId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<int> Year { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string Trim { get; set; }
        public Nullable<int> Mileage { get; set; }
        public string Vin { get; set; }
        public string SelectedOptions { get; set; }
        public string Condition { get; set; }
        public Nullable<int> ChromeTrimId { get; set; }
        public Nullable<decimal> TradeInFairValue { get; set; }
        public Nullable<decimal> TradeInMaxValue { get; set; }
        public int DealerId { get; set; }
        public Nullable<decimal> VarianceValue { get; set; }
        public string Source { get; set; }
        public string TradeInStatus { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
    
        public virtual Dealer Dealer { get; set; }
    }
}
