//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vincontrol.WebAPI.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradeInComment
    {
        public int TradeInCommentId { get; set; }
        public string Content { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public int DealerId { get; set; }
        public Nullable<System.DateTime> CommentDate { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
    
        public virtual Dealer Dealer { get; set; }
    }
}
