//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vincontrol.WebAPI.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrimOption
    {
        public int TrimOptionId { get; set; }
        public int TrimId { get; set; }
        public int OptionId { get; set; }
    
        public virtual Option Option { get; set; }
        public virtual Trim Trim { get; set; }
    }
}
