//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vincontrol.WebAPI.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trim
    {
        public Trim()
        {
            this.TrimOptions = new HashSet<TrimOption>();
        }
    
        public int TrimId { get; set; }
        public string StyleName { get; set; }
        public long ChromeId { get; set; }
        public int ModelId { get; set; }
        public bool IsDefault { get; set; }
        public Nullable<int> KBBTrimId { get; set; }
        public Nullable<int> ManheimTrimId { get; set; }
        public string DefaultImageUrl { get; set; }
        public string TrimName { get; set; }
        public string Code { get; set; }
    
        public virtual Model Model { get; set; }
        public virtual ICollection<TrimOption> TrimOptions { get; set; }
    }
}
