//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vincontrol.WebAPI.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrimPackage
    {
        public int TrimPackageId { get; set; }
        public int TrimId { get; set; }
        public int PackageId { get; set; }
    
        public virtual Package Package { get; set; }
    }
}
