//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vincontrol.WebAPI.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDealerActivity
    {
        public int UserDealerActivityId { get; set; }
        public string Detail { get; set; }
        public Nullable<int> UserId { get; set; }
        public int DealerId { get; set; }
        public System.DateTime DateStamp { get; set; }
        public short DealerActivitySubTypeCodeId { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Role { get; set; }
        public int UserStampId { get; set; }
    
        public virtual DealerActivitySubTypeCode DealerActivitySubTypeCode { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
