//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vincontrol.WebAPI.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserNotification
    {
        public int UserNotificationId { get; set; }
        public int UserId { get; set; }
        public int DealerId { get; set; }
        public Nullable<System.DateTime> DateStamp { get; set; }
        public bool AppraisalNotified { get; set; }
        public bool WholesaleNotified { get; set; }
        public bool InventoryNotified { get; set; }
        public bool C24hNotified { get; set; }
        public bool NoteNotified { get; set; }
        public bool PriceChangeNotified { get; set; }
        public bool AgingNotified { get; set; }
        public bool BucketJumpNotified { get; set; }
        public bool MarketPriceRangeNotified { get; set; }
        public bool ImageUploadNotified { get; set; }
    
        public virtual Dealer Dealer { get; set; }
        public virtual User User { get; set; }
    }
}
