//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vincontrol.WebAPI.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Appraisals = new HashSet<Appraisal>();
            this.Appraisals1 = new HashSet<Appraisal>();
            this.AppraisalDealerActivities = new HashSet<AppraisalDealerActivity>();
            this.FlyerShareDealerActivities = new HashSet<FlyerShareDealerActivity>();
            this.Inventories = new HashSet<Inventory>();
            this.InventoryDealerActivities = new HashSet<InventoryDealerActivity>();
            this.SoldoutInventories = new HashSet<SoldoutInventory>();
            this.UserDealerActivities = new HashSet<UserDealerActivity>();
            this.UserDealerActivities1 = new HashSet<UserDealerActivity>();
            this.UserNotifications = new HashSet<UserNotification>();
            this.UserPermissions = new HashSet<UserPermission>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public System.DateTime Expiration { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string CellPhone { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> DefaultLogin { get; set; }
        public string DealerGroupId { get; set; }
        public Nullable<int> OldUserId { get; set; }
    
        public virtual ICollection<Appraisal> Appraisals { get; set; }
        public virtual ICollection<Appraisal> Appraisals1 { get; set; }
        public virtual ICollection<AppraisalDealerActivity> AppraisalDealerActivities { get; set; }
        public virtual DealerGroup DealerGroup { get; set; }
        public virtual ICollection<FlyerShareDealerActivity> FlyerShareDealerActivities { get; set; }
        public virtual ICollection<Inventory> Inventories { get; set; }
        public virtual ICollection<InventoryDealerActivity> InventoryDealerActivities { get; set; }
        public virtual ICollection<SoldoutInventory> SoldoutInventories { get; set; }
        public virtual ICollection<UserDealerActivity> UserDealerActivities { get; set; }
        public virtual ICollection<UserDealerActivity> UserDealerActivities1 { get; set; }
        public virtual ICollection<UserNotification> UserNotifications { get; set; }
        public virtual ICollection<UserPermission> UserPermissions { get; set; }
    }
}
