//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vincontrol.WebAPI.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public Vehicle()
        {
            this.Appraisals = new HashSet<Appraisal>();
            this.Inventories = new HashSet<Inventory>();
            this.SoldoutInventories = new HashSet<SoldoutInventory>();
            this.TradeInPriceAlerts = new HashSet<TradeInPriceAlert>();
        }
    
        public int VehicleId { get; set; }
        public Nullable<int> Year { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string Trim { get; set; }
        public string Vin { get; set; }
        public Nullable<decimal> Msrp { get; set; }
        public string InteriorColor { get; set; }
        public string BodyType { get; set; }
        public Nullable<int> Cylinders { get; set; }
        public Nullable<double> Litter { get; set; }
        public string EngineType { get; set; }
        public string DriveTrain { get; set; }
        public string FuelType { get; set; }
        public string Tranmission { get; set; }
        public Nullable<int> Doors { get; set; }
        public string FuelEconomyCity { get; set; }
        public string FuelEconomyHighWay { get; set; }
        public string StandardOptions { get; set; }
        public Nullable<int> KBBEngineId { get; set; }
        public Nullable<int> KBBTransmissionId { get; set; }
        public Nullable<int> KBBDriveTrainId { get; set; }
        public string KBBOptionsId { get; set; }
        public Nullable<int> KBBTrimId { get; set; }
        public Nullable<decimal> MarketLowestPrice { get; set; }
        public Nullable<decimal> MarketAveragePrice { get; set; }
        public Nullable<decimal> MarketHighestPrice { get; set; }
        public string ColorCode { get; set; }
        public Nullable<int> NumberOfCar { get; set; }
        public string ChromeStyleId { get; set; }
        public string ChromeModelId { get; set; }
        public Nullable<int> ManheimTrimId { get; set; }
        public Nullable<short> VehicleType { get; set; }
        public string DefaultStockImage { get; set; }
        public Nullable<bool> OldIsWholesale { get; set; }
        public Nullable<int> OldAppraisalId { get; set; }
        public Nullable<int> OldInventoryId { get; set; }
        public Nullable<int> OldSoldoutInventoryId { get; set; }
    
        public virtual ICollection<Appraisal> Appraisals { get; set; }
        public virtual ICollection<Inventory> Inventories { get; set; }
        public virtual ICollection<SoldoutInventory> SoldoutInventories { get; set; }
        public virtual ICollection<TradeInPriceAlert> TradeInPriceAlerts { get; set; }
    }
}
