//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vincontrol.WebAPI.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleStatusCode
    {
        public VehicleStatusCode()
        {
            this.BucketJumpHistories = new HashSet<BucketJumpHistory>();
            this.ChartSelections = new HashSet<ChartSelection>();
            this.KellyBlueBooks = new HashSet<KellyBlueBook>();
            this.ManheimValues = new HashSet<ManheimValue>();
            this.PriceChangeHistories = new HashSet<PriceChangeHistory>();
        }
    
        public short VehicleStatusCodeId { get; set; }
        public string Value { get; set; }
    
        public virtual ICollection<BucketJumpHistory> BucketJumpHistories { get; set; }
        public virtual ICollection<ChartSelection> ChartSelections { get; set; }
        public virtual ICollection<KellyBlueBook> KellyBlueBooks { get; set; }
        public virtual ICollection<ManheimValue> ManheimValues { get; set; }
        public virtual ICollection<PriceChangeHistory> PriceChangeHistories { get; set; }
    }
}
