//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vincontrol.WebAPI.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VincaptureDesktopTool
    {
        public int VersionId { get; set; }
        public int VersionNumber { get; set; }
        public System.DateTime ReleaseDate { get; set; }
    }
}
