//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vincontrol.WebAPI.DatabaseModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VINcontrolEntities : DbContext
    {
        public VINcontrolEntities()
            : base("name=VINcontrolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Answer> Answers { get; set; }
        public DbSet<Appraisal> Appraisals { get; set; }
        public DbSet<AppraisalCustomer> AppraisalCustomers { get; set; }
        public DbSet<AppraisalDealerActivity> AppraisalDealerActivities { get; set; }
        public DbSet<AppraisalStatusCode> AppraisalStatusCodes { get; set; }
        public DbSet<AutoTrader> AutoTraders { get; set; }
        public DbSet<AutoTraderDealer> AutoTraderDealers { get; set; }
        public DbSet<BlackBook> BlackBooks { get; set; }
        public DbSet<BucketJumpHistory> BucketJumpHistories { get; set; }
        public DbSet<Button> Buttons { get; set; }
        public DbSet<BuyerGuide> BuyerGuides { get; set; }
        public DbSet<Carfax> Carfaxes { get; set; }
        public DbSet<ChartSelection> ChartSelections { get; set; }
        public DbSet<DataFeedCompany> DataFeedCompanies { get; set; }
        public DbSet<DataFeedDealer> DataFeedDealers { get; set; }
        public DbSet<Dealer> Dealers { get; set; }
        public DbSet<DealerActivitySubTypeCode> DealerActivitySubTypeCodes { get; set; }
        public DbSet<DealerActivityTypeCode> DealerActivityTypeCodes { get; set; }
        public DbSet<DealerButton> DealerButtons { get; set; }
        public DbSet<DealerGroup> DealerGroups { get; set; }
        public DbSet<Description> Descriptions { get; set; }
        public DbSet<DescriptionTemplate> DescriptionTemplates { get; set; }
        public DbSet<Ebay> Ebays { get; set; }
        public DbSet<EbayCategory> EbayCategories { get; set; }
        public DbSet<FlyerShareDealerActivity> FlyerShareDealerActivities { get; set; }
        public DbSet<Inventory> Inventories { get; set; }
        public DbSet<InventoryDealerActivity> InventoryDealerActivities { get; set; }
        public DbSet<InventoryStatusCode> InventoryStatusCodes { get; set; }
        public DbSet<KellyBlueBook> KellyBlueBooks { get; set; }
        public DbSet<Make> Makes { get; set; }
        public DbSet<ManheimMake> ManheimMakes { get; set; }
        public DbSet<ManheimMakeModel> ManheimMakeModels { get; set; }
        public DbSet<ManheimModel> ManheimModels { get; set; }
        public DbSet<ManheimModelTrim> ManheimModelTrims { get; set; }
        public DbSet<ManheimTrim> ManheimTrims { get; set; }
        public DbSet<ManheimValue> ManheimValues { get; set; }
        public DbSet<ManheimYearMake> ManheimYearMakes { get; set; }
        public DbSet<MarketSourceCode> MarketSourceCodes { get; set; }
        public DbSet<Model> Models { get; set; }
        public DbSet<NotificationSetting> NotificationSettings { get; set; }
        public DbSet<NotificationTypeCode> NotificationTypeCodes { get; set; }
        public DbSet<Option> Options { get; set; }
        public DbSet<Package> Packages { get; set; }
        public DbSet<PermissionCode> PermissionCodes { get; set; }
        public DbSet<PermissionValue> PermissionValues { get; set; }
        public DbSet<PriceChangeHistory> PriceChangeHistories { get; set; }
        public DbSet<Question> Questions { get; set; }
        public DbSet<QuestionType> QuestionTypes { get; set; }
        public DbSet<Rebate> Rebates { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<RolePermission> RolePermissions { get; set; }
        public DbSet<Sentence> Sentences { get; set; }
        public DbSet<SentenceType> SentenceTypes { get; set; }
        public DbSet<Setting> Settings { get; set; }
        public DbSet<SoldoutInventory> SoldoutInventories { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TradeInComment> TradeInComments { get; set; }
        public DbSet<TradeInCustomer> TradeInCustomers { get; set; }
        public DbSet<TradeInPriceAlert> TradeInPriceAlerts { get; set; }
        public DbSet<Trim> Trims { get; set; }
        public DbSet<TrimOption> TrimOptions { get; set; }
        public DbSet<TrimPackage> TrimPackages { get; set; }
        public DbSet<TruckCategory> TruckCategories { get; set; }
        public DbSet<UsaZipCode> UsaZipCodes { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<UserDealerActivity> UserDealerActivities { get; set; }
        public DbSet<UserNotification> UserNotifications { get; set; }
        public DbSet<UserPermission> UserPermissions { get; set; }
        public DbSet<Vehicle> Vehicles { get; set; }
        public DbSet<VehicleStatusCode> VehicleStatusCodes { get; set; }
        public DbSet<VincaptureDesktopTool> VincaptureDesktopTools { get; set; }
        public DbSet<VPContactInfo> VPContactInfoes { get; set; }
        public DbSet<Walkaround> Walkarounds { get; set; }
        public DbSet<WarrantyType> WarrantyTypes { get; set; }
        public DbSet<YearMake> YearMakes { get; set; }
    }
}
