//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vincontrol.WebAPI.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VPContactInfo
    {
        public int VPContactInfoId { get; set; }
        public int DealerId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string FriendName { get; set; }
        public string ContactPrefer { get; set; }
        public Nullable<int> ContactType { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<int> Postal { get; set; }
        public string Email { get; set; }
        public string FriendEmail { get; set; }
        public string Phone { get; set; }
        public string Vin { get; set; }
        public string Stock { get; set; }
        public Nullable<int> Year { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string Engine { get; set; }
        public string Trim { get; set; }
        public string Transmission { get; set; }
        public string ExteriorColor { get; set; }
        public Nullable<int> Mileage { get; set; }
        public string Condition { get; set; }
        public string Options { get; set; }
        public string ServiceType { get; set; }
        public Nullable<int> OfferValue { get; set; }
        public string JobTitle { get; set; }
        public Nullable<int> SpecialId { get; set; }
        public string SpecialCategory { get; set; }
        public Nullable<int> TemplateType { get; set; }
        public string CL { get; set; }
        public string CV { get; set; }
        public string Comment { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> ScheduleDate { get; set; }
        public string ScheduleTime { get; set; }
        public string RequestLink { get; set; }
        public Nullable<bool> SubmitFlag { get; set; }
        public Nullable<bool> ReadFlag { get; set; }
        public Nullable<bool> FavoriteFlag { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
    }
}
