//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vincontrol.WebAPI.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Walkaround
    {
        public int WalkaroundId { get; set; }
        public Nullable<int> Order { get; set; }
        public Nullable<double> X { get; set; }
        public Nullable<double> Y { get; set; }
        public string Note { get; set; }
        public int AppraisalId { get; set; }
        public Nullable<int> OldAppraisalId { get; set; }
    
        public virtual Appraisal Appraisal { get; set; }
    }
}
