//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vincontrol.WebAPI.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarrantyType
    {
        public int WarrantyTypeId { get; set; }
        public string Name { get; set; }
        public int DealerId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> Category { get; set; }
    
        public virtual Dealer Dealer { get; set; }
    }
}
