//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vincontrol.WebAPI.DatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class YearMake
    {
        public YearMake()
        {
            this.Models = new HashSet<Model>();
        }
    
        public int YearMakeId { get; set; }
        public int MakeId { get; set; }
        public int Year { get; set; }
    
        public virtual Make Make { get; set; }
        public virtual ICollection<Model> Models { get; set; }
    }
}
