//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace Vincontrol.Payment.com.securenet.certify {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SPOSServerSoap", Namespace="https://gateway.securenet.com/sposws/")]
    public partial class SPOSServer : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ValidateLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateSNETOperationCompleted;
        
        private System.Threading.SendOrPostCallback ChangePasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback GroupListOperationCompleted;
        
        private System.Threading.SendOrPostCallback FindTransactionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SPOSServer() {
            this.Url = global::Vincontrol.Payment.Properties.Settings.Default.Vincontrol_Payment_com_securenet_certify_SPOSServer;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ValidateLoginCompletedEventHandler ValidateLoginCompleted;
        
        /// <remarks/>
        public event UpdateSNETCompletedEventHandler UpdateSNETCompleted;
        
        /// <remarks/>
        public event ChangePasswordCompletedEventHandler ChangePasswordCompleted;
        
        /// <remarks/>
        public event GroupListCompletedEventHandler GroupListCompleted;
        
        /// <remarks/>
        public event FindTransactionCompletedEventHandler FindTransactionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://gateway.securenet.com/sposws/ValidateLogin", RequestNamespace="https://gateway.securenet.com/sposws/", ResponseNamespace="https://gateway.securenet.com/sposws/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SPOSParams ValidateLogin(string username, string password, string Unlock) {
            object[] results = this.Invoke("ValidateLogin", new object[] {
                        username,
                        password,
                        Unlock});
            return ((SPOSParams)(results[0]));
        }
        
        /// <remarks/>
        public void ValidateLoginAsync(string username, string password, string Unlock) {
            this.ValidateLoginAsync(username, password, Unlock, null);
        }
        
        /// <remarks/>
        public void ValidateLoginAsync(string username, string password, string Unlock, object userState) {
            if ((this.ValidateLoginOperationCompleted == null)) {
                this.ValidateLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateLoginOperationCompleted);
            }
            this.InvokeAsync("ValidateLogin", new object[] {
                        username,
                        password,
                        Unlock}, this.ValidateLoginOperationCompleted, userState);
        }
        
        private void OnValidateLoginOperationCompleted(object arg) {
            if ((this.ValidateLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateLoginCompleted(this, new ValidateLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://gateway.securenet.com/sposws/UpdateSNET", RequestNamespace="https://gateway.securenet.com/sposws/", ResponseNamespace="https://gateway.securenet.com/sposws/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SPOSParams UpdateSNET(string UserID, string SecurenetID, string GroupID, string Unlock) {
            object[] results = this.Invoke("UpdateSNET", new object[] {
                        UserID,
                        SecurenetID,
                        GroupID,
                        Unlock});
            return ((SPOSParams)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateSNETAsync(string UserID, string SecurenetID, string GroupID, string Unlock) {
            this.UpdateSNETAsync(UserID, SecurenetID, GroupID, Unlock, null);
        }
        
        /// <remarks/>
        public void UpdateSNETAsync(string UserID, string SecurenetID, string GroupID, string Unlock, object userState) {
            if ((this.UpdateSNETOperationCompleted == null)) {
                this.UpdateSNETOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateSNETOperationCompleted);
            }
            this.InvokeAsync("UpdateSNET", new object[] {
                        UserID,
                        SecurenetID,
                        GroupID,
                        Unlock}, this.UpdateSNETOperationCompleted, userState);
        }
        
        private void OnUpdateSNETOperationCompleted(object arg) {
            if ((this.UpdateSNETCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateSNETCompleted(this, new UpdateSNETCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://gateway.securenet.com/sposws/ChangePassword", RequestNamespace="https://gateway.securenet.com/sposws/", ResponseNamespace="https://gateway.securenet.com/sposws/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ChangePassword(string UserID, string SecurenetID, string GroupID, string NewPassword, string OldPassword, string Unlock) {
            object[] results = this.Invoke("ChangePassword", new object[] {
                        UserID,
                        SecurenetID,
                        GroupID,
                        NewPassword,
                        OldPassword,
                        Unlock});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ChangePasswordAsync(string UserID, string SecurenetID, string GroupID, string NewPassword, string OldPassword, string Unlock) {
            this.ChangePasswordAsync(UserID, SecurenetID, GroupID, NewPassword, OldPassword, Unlock, null);
        }
        
        /// <remarks/>
        public void ChangePasswordAsync(string UserID, string SecurenetID, string GroupID, string NewPassword, string OldPassword, string Unlock, object userState) {
            if ((this.ChangePasswordOperationCompleted == null)) {
                this.ChangePasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChangePasswordOperationCompleted);
            }
            this.InvokeAsync("ChangePassword", new object[] {
                        UserID,
                        SecurenetID,
                        GroupID,
                        NewPassword,
                        OldPassword,
                        Unlock}, this.ChangePasswordOperationCompleted, userState);
        }
        
        private void OnChangePasswordOperationCompleted(object arg) {
            if ((this.ChangePasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChangePasswordCompleted(this, new ChangePasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://gateway.securenet.com/sposws/GroupList", RequestNamespace="https://gateway.securenet.com/sposws/", ResponseNamespace="https://gateway.securenet.com/sposws/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GroupList(string GroupID, string UserID, string Unlock) {
            object[] results = this.Invoke("GroupList", new object[] {
                        GroupID,
                        UserID,
                        Unlock});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GroupListAsync(string GroupID, string UserID, string Unlock) {
            this.GroupListAsync(GroupID, UserID, Unlock, null);
        }
        
        /// <remarks/>
        public void GroupListAsync(string GroupID, string UserID, string Unlock, object userState) {
            if ((this.GroupListOperationCompleted == null)) {
                this.GroupListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGroupListOperationCompleted);
            }
            this.InvokeAsync("GroupList", new object[] {
                        GroupID,
                        UserID,
                        Unlock}, this.GroupListOperationCompleted, userState);
        }
        
        private void OnGroupListOperationCompleted(object arg) {
            if ((this.GroupListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GroupListCompleted(this, new GroupListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://gateway.securenet.com/sposws/FindTransaction", RequestNamespace="https://gateway.securenet.com/sposws/", ResponseNamespace="https://gateway.securenet.com/sposws/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TransactionResponseData FindTransaction(string SecurenetID, string SecureKey, string TransactionID) {
            object[] results = this.Invoke("FindTransaction", new object[] {
                        SecurenetID,
                        SecureKey,
                        TransactionID});
            return ((TransactionResponseData)(results[0]));
        }
        
        /// <remarks/>
        public void FindTransactionAsync(string SecurenetID, string SecureKey, string TransactionID) {
            this.FindTransactionAsync(SecurenetID, SecureKey, TransactionID, null);
        }
        
        /// <remarks/>
        public void FindTransactionAsync(string SecurenetID, string SecureKey, string TransactionID, object userState) {
            if ((this.FindTransactionOperationCompleted == null)) {
                this.FindTransactionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFindTransactionOperationCompleted);
            }
            this.InvokeAsync("FindTransaction", new object[] {
                        SecurenetID,
                        SecureKey,
                        TransactionID}, this.FindTransactionOperationCompleted, userState);
        }
        
        private void OnFindTransactionOperationCompleted(object arg) {
            if ((this.FindTransactionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FindTransactionCompleted(this, new FindTransactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://gateway.securenet.com/sposws/")]
    public partial class SPOSParams {
        
        private bool isADMINField;
        
        private bool rEFUNDField;
        
        private bool vOIDField;
        
        private bool sALEField;
        
        private bool cAPTUREField;
        
        private int uSERIDField;
        
        private int groupIDField;
        
        private int gatewayIDField;
        
        private string resellerIDField;
        
        private string passwordPromptField;
        
        private string companyNameField;
        
        private string userNameField;
        
        private string nameField;
        
        private int iSOIdField;
        
        private string address1Field;
        
        private string address2Field;
        
        private string cityField;
        
        private string stateField;
        
        private string zipField;
        
        private string countryField;
        
        private string phoneField;
        
        private string faxField;
        
        private string adminEmailAddressField;
        
        private string securenetIDField;
        
        private string secureKeyField;
        
        private string messageField;
        
        private bool isValidField;
        
        private bool loadKeyField;
        
        private bool autoLoginField;
        
        private string industryCodeField;
        
        /// <remarks/>
        public bool isADMIN {
            get {
                return this.isADMINField;
            }
            set {
                this.isADMINField = value;
            }
        }
        
        /// <remarks/>
        public bool REFUND {
            get {
                return this.rEFUNDField;
            }
            set {
                this.rEFUNDField = value;
            }
        }
        
        /// <remarks/>
        public bool VOID {
            get {
                return this.vOIDField;
            }
            set {
                this.vOIDField = value;
            }
        }
        
        /// <remarks/>
        public bool SALE {
            get {
                return this.sALEField;
            }
            set {
                this.sALEField = value;
            }
        }
        
        /// <remarks/>
        public bool CAPTURE {
            get {
                return this.cAPTUREField;
            }
            set {
                this.cAPTUREField = value;
            }
        }
        
        /// <remarks/>
        public int USERID {
            get {
                return this.uSERIDField;
            }
            set {
                this.uSERIDField = value;
            }
        }
        
        /// <remarks/>
        public int GroupID {
            get {
                return this.groupIDField;
            }
            set {
                this.groupIDField = value;
            }
        }
        
        /// <remarks/>
        public int GatewayID {
            get {
                return this.gatewayIDField;
            }
            set {
                this.gatewayIDField = value;
            }
        }
        
        /// <remarks/>
        public string ResellerID {
            get {
                return this.resellerIDField;
            }
            set {
                this.resellerIDField = value;
            }
        }
        
        /// <remarks/>
        public string PasswordPrompt {
            get {
                return this.passwordPromptField;
            }
            set {
                this.passwordPromptField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int ISOId {
            get {
                return this.iSOIdField;
            }
            set {
                this.iSOIdField = value;
            }
        }
        
        /// <remarks/>
        public string Address1 {
            get {
                return this.address1Field;
            }
            set {
                this.address1Field = value;
            }
        }
        
        /// <remarks/>
        public string Address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string Zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string Fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
            }
        }
        
        /// <remarks/>
        public string AdminEmailAddress {
            get {
                return this.adminEmailAddressField;
            }
            set {
                this.adminEmailAddressField = value;
            }
        }
        
        /// <remarks/>
        public string SecurenetID {
            get {
                return this.securenetIDField;
            }
            set {
                this.securenetIDField = value;
            }
        }
        
        /// <remarks/>
        public string SecureKey {
            get {
                return this.secureKeyField;
            }
            set {
                this.secureKeyField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public bool isValid {
            get {
                return this.isValidField;
            }
            set {
                this.isValidField = value;
            }
        }
        
        /// <remarks/>
        public bool LoadKey {
            get {
                return this.loadKeyField;
            }
            set {
                this.loadKeyField = value;
            }
        }
        
        /// <remarks/>
        public bool AutoLogin {
            get {
                return this.autoLoginField;
            }
            set {
                this.autoLoginField = value;
            }
        }
        
        /// <remarks/>
        public string IndustryCode {
            get {
                return this.industryCodeField;
            }
            set {
                this.industryCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://gateway.securenet.com/sposws/")]
    public partial class TransactionResponseData {
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string response_CodeField;
        
        private string response_SubcodeField;
        
        private string response_Reason_CodeField;
        
        private string response_Reason_TextField;
        
        private string approval_CodeField;
        
        private string aVS_Result_CodeField;
        
        private string card_Code_Response_CodeField;
        
        private string cAVV_Response_CodeField;
        
        private string transaction_IDField;
        
        private string order_IDField;
        
        private string amountField;
        
        private string methodField;
        
        private string transaction_TypeField;
        
        private string customer_IDField;
        
        private string cardholder_FirstNameField;
        
        private string cardholder_LastNameField;
        
        private string bank_ACCNT_NameField;
        
        private string companyField;
        
        private string billing_AddressField;
        
        private string cityField;
        
        private string stateField;
        
        private string zipField;
        
        private string countryField;
        
        private string phoneField;
        
        private string emailField;
        
        private string level2_ValidField;
        
        private string level3_ValidField;
        
        private string additionalData1Field;
        
        private string additionalData2Field;
        
        private string cardTypeField;
        
        private string batchIDField;
        
        private string transactionDateTimeField;
        
        private string settlementDateTimeField;
        
        private string last4DigitsField;
        
        private string expiryDateField;
        
        private string gratuityAmountField;
        
        private string settlementAmountField;
        
        private string checkNoField;
        
        private string bank_aba_codeField;
        
        private string bank_acct_typeField;
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string Response_Code {
            get {
                return this.response_CodeField;
            }
            set {
                this.response_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Response_Subcode {
            get {
                return this.response_SubcodeField;
            }
            set {
                this.response_SubcodeField = value;
            }
        }
        
        /// <remarks/>
        public string Response_Reason_Code {
            get {
                return this.response_Reason_CodeField;
            }
            set {
                this.response_Reason_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Response_Reason_Text {
            get {
                return this.response_Reason_TextField;
            }
            set {
                this.response_Reason_TextField = value;
            }
        }
        
        /// <remarks/>
        public string Approval_Code {
            get {
                return this.approval_CodeField;
            }
            set {
                this.approval_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string AVS_Result_Code {
            get {
                return this.aVS_Result_CodeField;
            }
            set {
                this.aVS_Result_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Card_Code_Response_Code {
            get {
                return this.card_Code_Response_CodeField;
            }
            set {
                this.card_Code_Response_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string CAVV_Response_Code {
            get {
                return this.cAVV_Response_CodeField;
            }
            set {
                this.cAVV_Response_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Transaction_ID {
            get {
                return this.transaction_IDField;
            }
            set {
                this.transaction_IDField = value;
            }
        }
        
        /// <remarks/>
        public string Order_ID {
            get {
                return this.order_IDField;
            }
            set {
                this.order_IDField = value;
            }
        }
        
        /// <remarks/>
        public string Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public string Method {
            get {
                return this.methodField;
            }
            set {
                this.methodField = value;
            }
        }
        
        /// <remarks/>
        public string Transaction_Type {
            get {
                return this.transaction_TypeField;
            }
            set {
                this.transaction_TypeField = value;
            }
        }
        
        /// <remarks/>
        public string Customer_ID {
            get {
                return this.customer_IDField;
            }
            set {
                this.customer_IDField = value;
            }
        }
        
        /// <remarks/>
        public string Cardholder_FirstName {
            get {
                return this.cardholder_FirstNameField;
            }
            set {
                this.cardholder_FirstNameField = value;
            }
        }
        
        /// <remarks/>
        public string Cardholder_LastName {
            get {
                return this.cardholder_LastNameField;
            }
            set {
                this.cardholder_LastNameField = value;
            }
        }
        
        /// <remarks/>
        public string Bank_ACCNT_Name {
            get {
                return this.bank_ACCNT_NameField;
            }
            set {
                this.bank_ACCNT_NameField = value;
            }
        }
        
        /// <remarks/>
        public string Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
            }
        }
        
        /// <remarks/>
        public string Billing_Address {
            get {
                return this.billing_AddressField;
            }
            set {
                this.billing_AddressField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string Zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Level2_Valid {
            get {
                return this.level2_ValidField;
            }
            set {
                this.level2_ValidField = value;
            }
        }
        
        /// <remarks/>
        public string Level3_Valid {
            get {
                return this.level3_ValidField;
            }
            set {
                this.level3_ValidField = value;
            }
        }
        
        /// <remarks/>
        public string AdditionalData1 {
            get {
                return this.additionalData1Field;
            }
            set {
                this.additionalData1Field = value;
            }
        }
        
        /// <remarks/>
        public string AdditionalData2 {
            get {
                return this.additionalData2Field;
            }
            set {
                this.additionalData2Field = value;
            }
        }
        
        /// <remarks/>
        public string CardType {
            get {
                return this.cardTypeField;
            }
            set {
                this.cardTypeField = value;
            }
        }
        
        /// <remarks/>
        public string BatchID {
            get {
                return this.batchIDField;
            }
            set {
                this.batchIDField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionDateTime {
            get {
                return this.transactionDateTimeField;
            }
            set {
                this.transactionDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public string SettlementDateTime {
            get {
                return this.settlementDateTimeField;
            }
            set {
                this.settlementDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public string Last4Digits {
            get {
                return this.last4DigitsField;
            }
            set {
                this.last4DigitsField = value;
            }
        }
        
        /// <remarks/>
        public string ExpiryDate {
            get {
                return this.expiryDateField;
            }
            set {
                this.expiryDateField = value;
            }
        }
        
        /// <remarks/>
        public string GratuityAmount {
            get {
                return this.gratuityAmountField;
            }
            set {
                this.gratuityAmountField = value;
            }
        }
        
        /// <remarks/>
        public string SettlementAmount {
            get {
                return this.settlementAmountField;
            }
            set {
                this.settlementAmountField = value;
            }
        }
        
        /// <remarks/>
        public string CheckNo {
            get {
                return this.checkNoField;
            }
            set {
                this.checkNoField = value;
            }
        }
        
        /// <remarks/>
        public string Bank_aba_code {
            get {
                return this.bank_aba_codeField;
            }
            set {
                this.bank_aba_codeField = value;
            }
        }
        
        /// <remarks/>
        public string Bank_acct_type {
            get {
                return this.bank_acct_typeField;
            }
            set {
                this.bank_acct_typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ValidateLoginCompletedEventHandler(object sender, ValidateLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SPOSParams Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SPOSParams)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void UpdateSNETCompletedEventHandler(object sender, UpdateSNETCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateSNETCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateSNETCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SPOSParams Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SPOSParams)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ChangePasswordCompletedEventHandler(object sender, ChangePasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChangePasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChangePasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GroupListCompletedEventHandler(object sender, GroupListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GroupListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GroupListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void FindTransactionCompletedEventHandler(object sender, FindTransactionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FindTransactionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FindTransactionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TransactionResponseData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TransactionResponseData)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591